cncf/mentoring

- README.md
This is a idea proposal related to CRI. The task is about integrate Unikernels as Kubernetes runtime by CRI, and using kubernetes/frakti project as intermediate since it is designed for hypervisor runtime. feiskyer & me from sig-node would like to mentor it. 
For more details please check the PR content.
For anyone not familiar with CRI design & implementation, please check this PR below: https://github.com/kubernetes/kubernetes/pull/17048, and [this blog](http://blog.kubernetes.io/2016/12/container-runtime-interface-cri-in-kubernetes.html)
cc @caniszczyk
> Idea for GSoC propsal of CRI

- README.md
This PR adds a reference to the list of Summer of Code ideas the gRPC project maintains at
https://github.com/grpc/grpc/blob/master/summerofcode/ideas.md
> Add gRPC Summer of Code projects link

- README.md
Hi CNCF,
Me (@resouer) and @Random-Liu from sig-node would like to propose a idea about integrating `KataContainers` with `containerd/cri-containerd`. 
@laijs, the core maintainer of Kata project will also join as mentor.
The goal will be like: users set up Kubernetes and cri-containerd, and then they can choose to run workloads with native containerd or Kata by annotations etc. This solution should work on both bare-metal and clouds (Kata supports nested virtualization).
Will be great to see two foundations join forces on Kubernetes.
cc @caniszczyk for review.
> Add a containerd + Kata idea

- README.md
For the reasons stated in the proposal, it would be nice to have tracing support in Kubernetes. As a start we could do the API handlers, and extend this to the entire code base gradually.
@caniszczyk @idvoretskyi @nikhita @sttts
> Add Kubernetes OpenTracing support topic

- README.md
This has since been implemented upstream, so we shouldn't be promoting this project here anymore.
@caniszczyk 
/cc @fabxc
> Remove weaveworks/mesh Alertmanager project

- README.md
gRPC has applied as a separate organization for GSoC: https://summerofcode.withgoogle.com/organizations/6309297353392128/
So we should remove it from the list of projects that come under CNCF.
/cc @caniszczyk @idvoretskyi @nathanielmanistaatgoogle
> Remove gRPC since they are a separate org for gsoc

- README.md
This pull request adds three project ideas from the [TUF](https://github.com/theupdateframework/tuf) project.
* Key rotation and explicit self-revocation
* Multi-role delegations
* Setting URLs for roles in the Root metadata file
Unrelated: It also removes two instances of trailing whitespace.
Mentors: @JustinCappos, @vladimir-v-diaz, and @awwad.
Signed-off-by: Vladimir Diaz \<vladimir.v.diaz@gmail.com>
> Add TUF project ideas to README

- README.md
Actually it's 3 CSI drivers projects which will be moved to kubernetes-sig finally (2 drivers are on progess in the repo migration)
https://github.com/csi-driver/azurefile-csi-driver  (based on azure disk)
https://github.com/csi-driver/azuredisk-csi-driver (based on azure file)
https://github.com/csi-driver/blobfuse-csi-driver  (based on azure storage)
> split GSOC idea into 3 sub projects

- README.md
Lots of mentors mentioned that they are getting an overwhelming amount of personal emails and DMs.
I'm not sure if I can say this for other CNCF projects, but for Kubernetes, we'd like to limit to using public channels unless necessary otherwise or if the mentor decides that they want to discuss things in a private channel.
Discussions in open source should be in the open and **DMs just don't scale**. :)
> Add note about using only public channels

- README.md
Just proposed two interesting GSoC topics related to ML + Kubernetes + Kubeflow.
/cc @caniszczyk @nikhita PTAL (and sorry for late propose ... )
> Init machine learning GSoC topics with Kuberentes + Kubeflow

- README.md
This PR removes projects for k/website from 2019 SOC.
> Remove k/website projects from 2019 SOC

- README.md
Adding a small table of contents for participating projects. This way it's easier to see at a glance which projects are participating this year, and to click directly to that project's ideas.
> Add Table of Contents for Projects

- README.md
Updated the TOC section to include CoreDNS project
> Add CoreDNS in TOC section

- communitybridge/README.md
Thanks to @palnabarun for catching this!
Community Bridge is not only for students, so this rewords to it to `applicants`.
cc @idvoretskyi
> communitybridge: remove student-specific wording

- communitybridge/README.md
This PR adds a CoreDNS project for autoscaling CoreDNS nodes. A bonus task
is to use machine learning for metrics to capacity transformation. We will
provide a starter machine learning algorithm to help getting started if
needed.
> Add CoreDNS project for autoscaling CoreDNS nodes

- communitybridge/README.md
Add another proposed project from the Thanos team with me as the mentor.
For this we will need a K8s cluster that we could use. @bwplotka @caniszczyk what are our options available here? If we will be able to have that then you could merge this.
Apologies for the late PR on Sunday. I should have enough time to take this on. We already have some things like `thanosbench` which will speed up this process.
> Thanos: add E2E benchmark project

- README.md
This PR adds two CoreDNS projects for Summer of Code, one is the external health check (and additional interaction with Kubernetes). Another is the anomaly detection of DNS (CoreDNS) server.
> Add CoreDNS projects for Summer of Code

- README.md
@krasi-georgiev suggested we add a separate task for running prombench on EKS to keep the option to divide the task if required.
cc: @gouthamve @krasi-georgiev 
Signed-off-by: Hrishikesh Barman <plain.hrishikeshbman@gmail.com>
> GSoC project suggestions : prometheus/test-infra ideas for EKS

- README.md
As requested on the GSoC Mentors list, add backup mentors for NYU Secure Systems Lab projects tuf and in-toto.
> Add mentors for tuf and in-toto soc 2020 projects

- README.md
Some progress has been already mentioned in the specified project. No need for it to be in GSoC.
/cc @krasi-georgiev
> Remove a project in Prometheus

- communitybridge/2020/q2/project_ideas.md
One of the projects listed for `prometheus/test-infra` didn't find good fit in SoC2020. I was thinking about adding it to the list for community-bridge projects.
Unfortunately, I think Prometheus is not enlisted as a project in the community-bridge website, nor have I applied to be a mentor for community-bridge. Is there any possibility to add this project and enroll prometheus as a project for it now? considering the fact that the submission deadline is close.
cc: @idvoretskyi 
Signed-off-by: Hrishikesh Barman <hrishikeshbman@gmail.com>
> Added prometheus/test-infra CommunityBridge Q2 project

- README.md
Organization admins are different for the different mentoring projects, removing listing from the top-level README file.
> Organization admins section updated

- summerofcode/README.md
We shuffled the mentors after getting the project sponsored by GSoC.
/cc @bwplotka @Harshitha1234
> Update Thanos metrics retention project to actual mentors

- README.md
Hello CNCF 👋 
I found that the community bridge is now LFX mentorship, but it's updated only on the folder and not on main README. So yeah, I thought it'd be nice if I change the name, not the link ;)
You can review the PR and decide. Thanks a ton
> Change CommunityBridge to LFX Program in README

- lfx-mentorship/2021/01-Spring/README.md
I am replacing the mentor positions of @negz for these projects.
> Replace @negz with @muvaf in Crossplane mentoring programs in 2021

- summerofcode/2021.md
This PR add CoreDNS project for GSoC 2021.
> Add CoreDNS project for GSoC 2021

- summerofcode/2021.md
This adds two GSoC 2021 project proposals for Tremor:
* The implementation of a Plugin system (PDK) to extend tremors functionality without recompilation.
* The addition of gRPC support as it is a defacto cloud-native standard interface.
> Add tremor GSoC2021 suggestions

- summerofcode/2021.md
This PR updates Summer-of-Code mentor for 2021 CoreDNS project
and adds Paul (@greenpau) as mentor as well.
> Update Summer-of-Code mentor for 2021 CoreDNS project

- seasonofdocs/README.md
This PR specifies that email is the only acceptable means of contact about Google Season of Docs 2021.
@celestehorgan 👋🏻  PTAL
> Email is the only acceptable means of contact

- lfx-mentorship/2021/02-Summer/project_ideas.md
This PR adds CoreDNS candidate project for LFX Mentorship
> Add CoreDNS candidate project for LFX Mentorship

- lfx-mentorship/2021/03-Fall/project_ideas.md
- Description: Users can use KubeVela to do application delivery and management. In this project, we hope to integrate KubeVela with developing time. So developers can have a consitent experience between local development and production deploy. There're multiple developing tools such as Tilt or Nocalhost, both of them can integrate with KubeVela by supporting KubeVela Application YAML.
- Recommended Skills: Golang, Kubernetes
- Mentor(s): Jianbo Sun (@wonderflow)
- Upstream Issue (URL): https://github.com/oam-dev/kubevela/issues/795
> add proposal for KubeVela

- lfx-mentorship/2021/03-Fall/project_ideas.md
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
- Description: This project aims to build an E2E Web dashboard that will display the CI/CD pipeline details of [scheduled](https://litmuschaos.github.io/litmus-e2e/generic-pipeline/pipeline-runs/pod-level-run.html) and [manual](https://github.com/litmuschaos/litmus-e2e/tree/master/.github/workflows) runs. It should contain all the litmus backend and portal pipelines and can be easily switched or add more pipelines. Currently, [these](https://github.com/litmuschaos/litmus-e2e/tree/master/.github/workflows) are the pipeline present in the e2e.
- Recommended Skills: Golang, ReactJS
- Mentor(s): Udit Gaurav (@uditgaurav)
- Upstream Issue (URL): https://github.com/litmuschaos/litmus/issues/3112
- Description: This project aims to develop/enhance …
> Adding two proposals for litmuschaos project

- lfx-mentorship/2021/03-Fall/project_ideas.md
Support remote Terraform HCL (Git repo or ConfigMap) in Terraform Controller
> Add a subproject of KubeVela: Support remote Terraform HCL (Git repo or ConfigMap) in Terraform Controller

- lfx-mentorship/2021/03-Fall/project_ideas.md
Document reorg, moving the "Migrate Thanos to the New Protocol Buffers v2 API" project idea into the Thanos org section.
> moving Thanos project idea into Thanos section

- lfx-mentorship/2022/01-Spring/project_ideas.md
- Description: [Chaos Mesh](https://chaos-mesh.org/) is a powerful chaos engineering platform for Kubernetes. There is a Katacoda playground as [interactive tutorial](https://chaos-mesh.org/interactive-tutorial/), and we want to build more Katacoda scenarios as the minimum examples for each certain type of chaos experiment. The basic work would be to create new katacoda scenarios as referred to by https://github.com/chaos-mesh/chaos-mesh/tree/master/examples, and build small applications (with well-built observability) as the target of chaos experiment if required. This project will not require you to dive deep into the hard-core parts of Chaos Mesh, instead, it would be a tour of learning and exploring Chaos Mesh.
- Recommended Skills: golang, Kubernetes, Shell scripts
- Mentor(s): …
> Add Chaos Mesh to LFX Mentorship Q1-2022

- lfx-mentorship/2022/01-Spring/project_ideas.md
This PR adds a project for improvising unit test coverage in Cluster API Provider vSphere, which is a Kubernetes SIG Cluster Lifecycle sub-project, to LFX spring term.
Signed-off-by: geetikab@vmware.com <geetikab@vmware.com>
> Add Cluster API Provider vSphere proposal to LFX Mentorship Spring 2022

- summerofcode/2022.md
Add GSoC KubeVela idea: Improve the capabilities of KubeVela GitOps to make it a standalone Addon
> KubeVela: Add GitOps addon for KubeVela

- summerofcode/2022.md
- Description: [LitmusChaos](https://litmuschaos.io) is an open-source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way. This project aims to develop a terraform provider or scripts to provision litmuschaos functionalities.
- Recommended Skills: Terraform, Kubernetes, Golang
- Mentor(s): @Jonsy13 @rajdas98 @Adarshkumar14
- Upstream Issue (URL): https://github.com/litmuschaos/litmus/issues/3456
> Adding LitmusChaos to GSoC 2022

- summerofcode/2022.md
As requested in https://github.com/cncf/mentoring/pull/480#issuecomment-1051311373, this updates the project description for Vitess' only GSoC proposal to be more comprehensive. Cheers!
> Update Vitess proposal for GSoC

- summerofcode/2022.md
This PR updates details for Cluster API Provider AWS GSoC 22 according to https://github.com/cncf/mentoring/issues/523.
> GSoC 2022: CAPA project update

- summerofcode/2022.md
Reverts cncf/mentoring#555
Undoing PR commit to check rules.
> Revert "GSoC 2022: update TiKV projects"

- summerofcode/2022.md
Reverts cncf/mentoring#556
Reverting, this should be ok.
> Revert "Revert "GSoC 2022: update TiKV projects""

- summerofcode/2022.md
While providing more info about the GSoC projects, we think more about the projects. Currently we send 4 projects, but project 1 is a part of project3, and project 4 is not suitable for a GSoC project. So we'd like to refactor the applied projects. Is it acceptable currently @nate-double-u? Sorry for the work.
> GSoC 2022: update TiKV projects

- lfx-mentorship/2022/02-Summer/README.md
The timeline `2021` must be a typo.
cc @nate-double-u
> Update LFX summer timeline

- lfx-mentorship/2022/02-Summer/README.md
Related to https://github.com/cncf/mentoring/discussions/632
I had already created a first PR to update `summerofcode/2022.md`.
But I figured out that the right path is probably `lfx-mentorship/2022/02-Summer/README.md` so I have created this.
> Adding GSoC 2022 ideas for the Devfile project (under `lfx-mentorship`)

- lfx-mentorship/2022/02-Summer/README.md
A small update to the proposed projects for the summer 2022 LFX
mentorship program. Cluster API Provider GCP would like to add support
for GPUs.
Signed-off-by: Richard Case <richard@weave.works>
/cc @dims @cpanato
> docs: add the CAPG GPU project

- lfx-mentorship/2022/02-Summer/README.md
Fixing a small issue with the link to the LFX project for summer 2022.
Signed-off-by: Richard Case <richard.case@outlook.com>
/cc @nate-double-u
> chore: fixed capg project url

- .github/settings.yml
Added details in 'collaborators' section as suggested by @nate-double-u re Mentoring initiative.
> Added username w/ 'maintain' permission

- lfx-mentorship/2022/03-Sept-Nov/README.md
Followup to https://github.com/cncf/mentoring/pull/676, extending 03-Sept-Nov `project proposal` date range by two days due to missed announcement. (again, missed a reference the first time)
> Updating LFX 03-Sept-Nov project proposal date range

- .github/settings.yml
Adding Dawn F., Josh B., and Carolyn VS. to settings.yml file as repo maintainers.
closes #679.
> Adding new repo maintainers

- .github/settings.yml
> Adding "time-sensitive" label for issues and PRs with due dates

- lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Use coder.com on CNCF INfrastructure to bring up pairing/mentoring
environments for our projects.
> Mentoring Workspaces - GITHUBUSER.PROJECT.cncf.io

- .github/settings.yml
Adding new TAG Contributor Strategy co-chair,  Catherine P. (@CathPag), to settings.yml file as repo maintainer.
> adding Catherine P. to settings.yml file as repo maintainer

- .github/settings.yml
Adding 'getting started' label for a common discussion thread topic.
Supercedes https://github.com/cncf/mentoring/pull/721. Sorry for the duplicated PR, didn't have time to hunt down  the DCO issues on the last one.
> Update settings.yml with new label

- summerofcode/2023.md
- summerofcode/README.md
Adding link to timeline, correcting formatting, updating README.
> updating GSoC 2023

- summerofcode/2023.md
Add Knative GSoC ideas we collected in our ideas page here: https://github.com/knative/community/blob/main/google-summer-of-code/gsoc-2023.md
> Add Knative GSoC ideas

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: Joe Kimmel <86852107+joe-kimmel-vmw@users.noreply.github.com>
> CNB profiling project for LFX spring 2023

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Adds the Kubewarden proposed project to the LFX mentorship program.
> Kubewarden LFX mentorship projects

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
> Feat: add wasmedge lfx mentorship 2023-01

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: Ben Ye <benye@amazon.com>
> Add project ideas for Thanos

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
This adds a project idea for the spring 23 mentorship program for the Cluster API Provider AWS project.
> doc: added cluster api provider aws project

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Project ideas for [Karmada](https://github.com/karmada-io/karmada) as part of the LFX Mentorship program.
> add ideas of Karmada project for lfx Mar-May 2023

- lfx-mentorship/2022/03-Sept-Nov/README.md
- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Adds proposed Kyverno mentorships for Spring '23 session.
> Kyverno mentorships

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Adds project for proposed NATS mentorship for Spring '23 session :)
Signed-off-by: Waldemar Quevedo <wally@nats.io>
> Add NATS project idea for LFX

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
This commit adds an LFX project for querying Apache Parquet files with the new Thanos PromQL engine.
Signed-off-by: Filip Petkovski <filip.petkovsky@gmail.com>
cc @onprem @yeya24 @GiedriusS
> Add LFX proposal for Parquet in PromQL

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Add the Kubescape LFX mentorship program ideas.
Signed-off-by: Craig Box <craigb@armosec.io>
> Add Kubescape suggestions

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: Joe Kimmel <86852107+joe-kimmel-vmw@users.noreply.github.com>
> buildpacks: propose arm/multi-arch project

- summerofcode/2023.md
Adding email addresses for some Knative mentors. Addressing the comment here: https://github.com/cncf/mentoring/pull/779/files#r1088070416
Signed-off-by: Ali Ok <aliok@redhat.com>
> Add emails for some Knative mentors

- lfx-mentorship/2023/01-Mar-May/project_ideas.md
Add Notary and ORAS project ideas to LFX mentorship program
cc @nate-double-u
> Add Notary and ORAS project ideas to lfx-mentorship

- lfx-mentorship/2023/01-Mar-May/README.md
- lfx-mentorship/README.md
Moving dates back one week across the term.
* updating LFX 2023 01-Mar-May dates. 
* Updating lfx-mentorship README with current term info.
> LFX 2023 01-Mar-May admin updates

- summerofcode/2023.md
Add a project of KubeVela in GSOC 2023.
Reference: https://github.com/kubevela/kubevela/issues/5366
> GSOC: KubeVela IDE Plugins

- summerofcode/2023.md
Removing the ToC from the proposed ideas page as it's causing too many merge conflicts.
We'll add it back at the end of the process. For now, just add the ideas to the list 🙂
> removing toc from GSoC 2023 proposed ideas page

- lfx-mentorship/2023/01-Mar-May/README.md
- lfx-mentorship/2023/01-Mar-May/project_ideas.md
adding TAG Contributor Strategy proposals
/hold till LFX approves
> Moving proposals to accepted (LFX Mentorship 2023 term 1: March - May)

- summerofcode/2023.md
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>
Provide two ideas for KubeVela:
1. Auto-generate the TypeScript and Java languages API SDK.
2. Expand multiple database drivers for the API server.
> GSOC: Add two ideas for KubeVela

- lfx-mentorship/2023/01-Mar-May/README.md
Signed-off-by: Ben Ye <benye@amazon.com>
CC @danielblando @qinxx108
> Add 2 mentors for LFX Cortex project

- summerofcode/2023.md
Signed-off-by: jefree-cat <jiahang_xu@cmbchina.com>
> GSOC: KubeVela HA Enhancement-Cluster Meta Backup&Restore

- summerofcode/2023.md
Some project ideas for Armada.
> Add project ideas for google summer of code for Armada

- .github/settings.yml
- lfx-mentorship/2023/02-Jun-Aug/README.md
- lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
- lfx-mentorship/2023/03-Sep-Nov/README.md
- lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Adding LFX Mentorship 2023 terms 2 & 3 timelines.
Things to note:
* KubeCon EU: 18 – 21 April 2023
* KubeCon NA: 6-9 November 2023
* This timeline doesn't set out a project proposals "open" timeline, just when they are due. I'd expect that two weeks out we'd still make a call for proposals like we normally do, but if projects want to submit proposals earlier they are able.
Deploy previews:
* https://github.com/nate-double-u/cncf-mentoring/tree/adding-lfx-2023-term-2-3/lfx-mentorship/2023/02-Jun-Aug
* https://github.com/nate-double-u/cncf-mentoring/tree/adding-lfx-2023-term-2-3/lfx-mentorship/2023/03-Sep-Nov
>  setting up CNCF LFX Mentorship 2023 Terms 02 & 03

- .github/settings.yml
I offered my help to co-admin GSoC efforts at CNCF and it was accepted in the WG meeting [notes](https://hackmd.io/@tag-cs-mentoring-wg/monthly-meeting-2023#Notes).
Adding myself as a maintainer so that I can "officially" review GSoC related PRs.
> Adding aliok as a repo maintainer (GSoC admin)

- .github/labeler.yml
- .github/workflows/prlabeler.yml
Please review and merge it, added pr labeling feature as per Open Issue [Automate labelling PRs #559](https://github.com/cncf/mentoring/issues/559)
- This workflow is based on github action official label action v4.
- This workflow action is triggered on pull request event(on both fork & inside repo)
- Labels will be applied based on filepath modification in PR.
- This workflow uses a regex based labeling config file(.github/labeler.yml) to take labeling decision.
> Fixed Automate labelling issue for fork PRs #559

- .github/labeler.yml
* Reorganizing prlabeller.yml. 
* Adding LFX term labels
> Updating prlabeller.yml

- summerofcode/2023.md
Related to https://github.com/cilium/tetragon/issues/794
> Add Cilium GSoC idea

- mentoring-wg/gsoc-org-admin-guide.md
- mentoring-wg/org-admins.md
Fixes https://github.com/cncf/mentoring/issues/201
GSoC admin guide:
- Targets v2 branch as there is no org admins section on current main branch
- Document contains general outline for the responsibilities of the GSoC admins and it provides detailed check-list kind of guide. I've seen examples in other communities [1](https://wiki.openmrs.org/display/RES/GSoC+Admin+Guidelines) [2](https://community.apache.org/gsoc-admin-tasks.html) and I think it might be useful.
- The check list is only complete for the GSoC phases we've been through in 2023 program. I will update it step by step when we reach future phases.
- "Contributor+proposal selection and ranking criteria" is discussed here and will be updated based on the outcome: https://github.com/cncf/mentoring/discussions/860
- "Contributor …
> GSoC admin guide

- summerofcode/2023.md
The applications are still open, can we add another Jaeger project idea?
> Add another Jaeger project

- .github/settings.yml
Remove labels that don't have any* open/closed issues labeled with it.
Some labels like `hold` are like the same but I am keeping it.
Fixes #933
> Remove labels that don't have any open/closed issues labeled with it

- programs/summerofcode/README.md
Fix link to GSoC 2023 program.
I saw there's a broken link when I was showing a GSoC related thing to people at KubeCon.
> Fix link to GSoC 2023 program

- .github/settings.yml
removing collaborator section of settings.yml as access is managed by sheriff over in https://github.com/cncf/people/commits/main/config.yaml now.
Are there other parts of this settings.yml file that should be updated/removed based on the sheriff setup?
> Removing collaborator section of settings.yml

- programs/lfx-mentorship/2023/02-Jun-Aug/README.md
The date for proposal due for mentors is Tuesday, 9th may. But there was a typo where it was mentioned the proposal due date is 4th May.
Tried to fix the issue in this PR :)
> Fix date mismatch with actual timeline

- .github/labeler.yml
fixes #939 
Removing `/` at the starts of the labeler.yml paths as i think that's what's broken.
> removing preceeding `/` in labeler.yml paths

- .vscode/settings.json
- mentoring-wg/gsoc-org-admin-guide.md
Checked all hyperlink in the repo.Found only one broken link which is fixed by this PR.
Some links in the meeting agendas do not work anymore, but this was part of work in progress. As it is part of historical agenda items, it should likely not be updated.
Fixes: #901
> Fix broken link

- programs/lfx-mentorship/2023/02-Jun-Aug/README.md
Add Albert Teoh as a co-mentor for the `Upgrade Jaeger's internal telemetry to OpenTelemetry` project for Jaeger.
> Add Albert Teoh as mentor for Jaeger

- mentors/README.md
Fixes: https://github.com/cncf/mentoring/issues/736
~~I've written the mentor guide here: https://docs.google.com/document/d/1Zozg3g5qE4jkdVEdiVtCoXvc_iuuOls1hfCgW6Pf7jQ/edit#heading=h.vpidi5cz3gv4~~
~~Happy to collect feedback there.~~
~~Later on, I will use this PR to update the markdown doc.~~
UPDATE: I've updated the doc with the content from the Google doc mentioned above
> Mentor guide

- programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
- Description: [LitmusChaos](https://litmuschaos.io) is an open-source chaos engineering platform for Kubernetes, enabling users to test and improve the resilience of their cloud-native applications. The project focuses on improving litmusctl by enhancing its interactive mode with promptui, and refactoring code to Go interfaces for better unit testing and code quality. Additionally, it aims to replace kubectl with client-go for more efficient Kubernetes operations, resulting in a more user-friendly and reliable command-line tool for chaos engineering and workload management.
- Expected outcome: The expected outcome of the project includes an improved litmusctl tool with a user-friendly promptui-based interactive mode, enhanced code quality through Go interfaces, and a robust test suite. …
> [Term-3]: Adding 2 LitmusChaos Project tasks for LFX Mentorship

- programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
This PR adds a topic idea from Kubernetes SIG Release for building library and CLI for interacting with OpenBuildService platform that we use for building and publishing packages.
cc @cpanato @saschagrunert
> lfx-fall-2023: Add K8s SIG Release topic idea

- programs/lfx-mentorship/2023/03-Sep-Nov/README.md
- programs/summerofcode/2023.md
The new one is my primary Linux Foundation account mail while the Red Hat one is only my secondary.
cc @nate-double-u @haircommander
> Fix email address for `saschagrunert`

- programs/lfx-mentorship/2023/03-Sep-Nov/README.md
Move Yash from **CNCF - Jaeger: Upgrade Jaeger UI to the latest version of React.js** to **CNCF → Jaeger: Combine three distinct graph views in Jaeger UI into one**
Resolves #1079
/cc @yurishkuro @yashrsharma44
> Update Jaeger mentors (moving Yash from one to another)

- README.md
<Signed-off-by: Ravi Kumar ravixis29@gmail.com>
> Corrected spelling mistakes

- programs/lfx-mentorship/2024/01-Mar-May/README.md
- programs/lfx-mentorship/2024/02-Jun-Aug/README.md
- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Planning LFX 2024 Term 2, Jun-Aug
previous timeline for term 2: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug
| activity | date |
| --- | --- |   
| project proposals | Monday April 8 - Wed April 24, 2024, 5:00 PM PDT |
| mentee applications open | Monday April 29 - Tues May 14, 5:00 PM PDT |
| application review/admission decisions | Wed May 15 - Tues June 29, 5:00 PM PDT |
| selection notifications | Tues May 29, 5:00 PM PDT |
| Mentorship program begins with the initial work assignments | Monday June 3 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | Wednesday July 10 10 (Week 6) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | Wed Aug 21, 5:00 PM PST (Week 12) | …
> Planning for LFX 2024 Term 02 Jun-Aug

- programs/summerofcode/2024.md
- programs/summerofcode/README.md
Once merged, post this message as an announcement:
```
Hello!
CNCF has been participating in the Google Summer of Code during the and now we are ready to start the 2024 program cycle.
All CNCF projects are eligible to apply to participate in the Google Summer of Code. Please start working on the project ideas, and submit them via pull request: https://github.com/cncf/mentoring/blob/main/summerofcode/2024.md#project-ideas. 
The deadline to submit project ideas is March 11, 2024 (though we'd be happy for project ideas to come in sooner than that if possible to increase our chance of getting accepted as an org).
[Google Summer of Code 2024 Timeline](https://developers.google.com/open-source/gsoc/timeline)
Thanks!
```
> Kick off GSoC 2024

- PROJECT_IDEA_TEMPLATE.md
- mentoring-wg/gsoc-org-admin-guide.md
- Update GSoC org admin guide with a reminders for mentors
- Update project template to encourage having a co-mentor (required for GSoC)
- Remove some obsolete content in org admin guide
GSoC support said that we are allowed to say that we require at least 2 mentors in an email.
> Update GSoC org admin guide with a reminders for mentors and project idea template for LFX to have multiple mentors

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
This PR adds Vitess's proposed parser project for the LFX Term 1 2024.
> Adds Vitess's proposed project for LFX 2024 term 01-Mar-May

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Adding Knative Eventing's Cross-Namespace Event Links project to the LFX mentorship program for March - May 2024
cc @aliok @pierdipi
> LFX: Add Knative eventing project for March - May term

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Adding Prometheus client_golang project idea
cc @kakkoyun @bwplotka
> Add Prometheus client_golang project idea

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Adding KCL package version management project to the LFX mentorship program for March - May 2024
> LFX: Add KCL project for March - May term

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Add project ideas for KubeVela community.
> feat: add kubevela lfx mentoring issue

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
This PR adds 4 Kyverno project ideas for 2024 Spring term.
> LFX menthorship: add Kyverno project ideas

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
This PR adds Kubearmor as part of LFX mentorship :D
> LFX: Add Kubearmor project for March - May term 2024

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> LFX Mentorship - OpenTelemetry - Mar 2024

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
This PR adds Inspektor Gadget as part of LFX mentorship.
https://github.com/inspektor-gadget/inspektor-gadget/
https://www.inspektor-gadget.io/
cc @mauriciovasquezbernal
> LFX Mentorship - Inspektor Gadget - Mar 2024

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Hi,  this pr adds Volcano project to the LFX mentorship program for March - May 2024
> LFX: Add Volcano project for 2024 March - May term

- programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Add project ideas for KubeEdge community.
> add KubeEdge project ideas for LFX March - May term

- programs/lfx-mentorship/2024/01-Mar-May/README.md
I would like to make some adjustments to the mentors for project https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/01-Mar-May#support-latest-version-in-keink-and-run-demo-on-keink.  Replace me with @HongbingZhang. 
Sorry for the extra work I've caused. Plz cc @nate-double-u  😃 
@HongbingZhang is one of TSC member of KubeEdge Community, he will serve as the mentor for the project
https://github.com/kubeedge/kubeedge/blob/master/MAINTAINERS.md#technical-steering-committee
> update mentors info for KubeEdge 2024 term1 projects 

- .github/labeler.yml
Fixes: https://github.com/cncf/mentoring/issues/1161
Adding GSoC 2024 to automatic labeller for "2024" label.
> Adding GSoC 2024 to auto labeller for "2024" label

- programs/summerofcode/2024.md
- Description: This task aims to implement comprehensive fuzzing test suites for our GraphQL interface and Authentication server ([ChaosCenter](https://github.com/litmuschaos/litmus/tree/master/chaoscenter)) to identify vulnerabilities and ensure robustness. The process involves developing targeted fuzzing strategies to thoroughly test these components and integrating the tests with [OSS-FUZZ](https://github.com/google/oss-fuzz) for automated fuzzing. This integration should streamline the process of monitoring and addressing potential security issues. The task also includes making the results accessible through the [ClusterFuzz Dashboard](https://google.github.io/clusterfuzz) for efficient management and analysis
- Expected Outcome:
- Comprehensive fuzzing test suites for the GraphQL …
> [GSOC]: Integration of Fuzzing Test Suites for LitmusChaos(ChaosCenter) with OSS-FUZZ

- programs/lfx-mentorship/2024/01-Mar-May/README.md
I've added a description to the list of projects, but not to the "accepted projects".
> Add Flux conformance tests to proposed projects for Mar->May 2024

- programs/summerofcode/2024.md
I would not be able to mentor the 2024 GSoC project due to time constraints. Hence updating the mentor list. Apologies for the inconvenience.
> [GSoC] Update Kubebuilder project mentor list

- programs/summerofcode/2024.md
Removing KubeVela project from GSoC 2024.
@FogDong, @chivalryq, as per my email, unfortunately, we need to remove this year's KubeVela project idea.
> Removing KubeVela project from GSoC 2024

- programs/summerofcode/2024.md
Adding CNCF and Google Open Source Security Team GSoC Collaboration - Enhancing Security Across CNCF Ecosystem Google Summer of Code 2024 project.
> adding CNCF GOSST GSoC Collaboration project idea

- programs/lfx-mentorship/2024/02-Jun-Aug/README.md
As we've had few project proposals, I'm shifting the semester back 2 weeks. This has the added benefit of giving mentors the chance to see if their GSoC projects were selected or not. Any declined GSoC project can be copied over to this LFX term verbatim.
> updating lfx 2024 term 2 dates to match better with GSoC calendar

- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Project for upcoming summer session related to benchmark testing of Prometheus Remote Write. Not sure if @jesusvazquez is already registered on the LFX mentorship platform.
> add prometheus remote write project for june 2024

- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Add project ideas for KubeEdge community.
> add KubeEdge project ideas for LFX Jun-Aug 2024

- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
This PR adds project ideas for Crossplane to the list of proposed projects for LFX Mentorship 2024 term 2, as per the instructions on https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/02-Jun-Aug/README.md#project-instructions.
> Add Crossplane project ideas for LFX 2024 term 2

- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
- programs/summerofcode/2024.md
> Add in-toto project ideas for LFX 2024 Term 2

- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
> Vitess community project for LFX 2024 Jun-Aug

- programs/lfx-mentorship/2024/02-Jun-Aug/README.md
- programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
ref https://github.com/kubernetes-sigs/kubespray/issues/5432
> Proposal of Kubespray project for LFX 2024 Jun-Aug

- programs/lfx-mentorship/2024/02-Jun-Aug/README.md
Hello 👋 , 
Made a mistake setting up my email when my LFX account to be used was under my personal email. I was trying to look at the list of applicants on the projects and realized I couldn't see either applicants or projects.
My bad for not suggesting the right email 🙏  Please let me know if there is anything else to do to fix this.
> Fix email on mentoring projects

- mentoring-wg/README.md
Update TAGCS Mentoring Working Group monthly meeting times to every third Thursday.
Adding current meeting minutes file.
> Update Mentoring WG Meeting times

- programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
> Add KCL lfx 2024-03 projects

- programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
> Fix links in Jaeger projects

- programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
> Add Prometheus Benchmarking project idea

- programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
cc @aknuds1
Opening as a draft because we're 2 Prometheus maintainers wanting to work on open-telemetry projects.
@dashpole, @aneurysm9, do we have your blessing to work on this? :)
> Add prometheus/otel project idea

- programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
Adding Harbor for Term 3 
Term 03 - 2024 September - October
> Add Harbor CLI and Harbor Satellite

- programs/lfx-mentorship/2024/03-Sep-Nov/README.md
Related to https://github.com/cncf/mentoring/issues/1297. Unsure if fixing the README also fixes the website, but this can't hurt. 
This slipped by, but I put https://github.com/konveyor/enhancements/issues/187 instead of the correct issue link https://github.com/konveyor/enhancements/issues/191 as the upstream issue for [CNCF - Konveyor AI: Data Querying for Kai & InstructLab Integration Potential](https://mentorship.lfx.linuxfoundation.org/project/8493016e-975f-4559-8833-db4c884b2fc5/mentees-past).
> Wrong repository link for "CNCF - Konveyor AI: Data Querying for Kai & InstructLab Integration Potential"

- programs/lfx-mentorship/2024/02-Jun-Aug/README.md
Fixes #1302
The description of term 2 was not updated from 12 weeks to 11 weeks when the dates were added.
The dates are correct, the description was too long.
> updating lfx 2023 term 2 description

- mentoring-wg/2024-meeting-minutes.md
Been a while since we've updated these. Easier now since Google docs allows markdown exports.
> updating 2024 TAG Mentoring WG meeting minutes

- programs/summerofcode/2025.md
- programs/summerofcode/README.md
Getting ready for GSoC 2025
https://summerofcode.withgoogle.com/programs/2025-ao
> Kick off GSoC 2025

- programs/lfx-mentorship/2025/02-Jun-Aug/README.md
- programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
- programs/lfx-mentorship/2025/03-Sep-Nov/README.md
- programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Proposed timelines for Term 2 & 3. We should double check the dates against Kubecons and Various national holidays.
| **Activity**                                                 | **Dates (2025)**                      | **Notes**                                                                                              |
|--------------------------------------------------------------|---------------------------------------|--------------------------------------------------------------------------------------------------------|
| **Project Proposals Open**                                   | Wed, April 16 – Tue, May 13             | ~4 weeks for mentors/orgs to propose projects. Ends the tuesday after GSoC projects are announced                                                |
| …
> adding plans for LFX 2025 T2 & T3

- programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
updated Add Harbor LFX 2025 term1 ideas.
cc // @Vad1mo, @OrlinVasilev
> Add Harbor projects for 2025 LFX Term 1

- programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Add KubeEdge LFX 2025 term1 ideas. PTAL 😄
> Add KubeEdge projects for 2025 LFX term1

- programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
> LFX: Add TUF project for Term 01

- programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
This PR adds projects for LFX Mentorship Program 2025 Term 1.
> Vitess: Added projects for  LFX Mentorship Program 2025 Term 1

- programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
> Thanos LFX 2025 Term 1 project idea

- programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Hi, team
This pr adds volcano project for LFX term 01 2025, thanks for your reviewing: )
> LFX: Add Volcano project for Term 01 - 2025 March - May

- programs/summerofcode/2025.md
Hi,
As discussed with @FeynmanZhou we would like to submit a mentorship idea for the ORAS Java SDK
I already mentored during GSoC 2024 for the jenkinsci organisation (https://www.jenkins.io/blog/2024/08/26/gsoc-using-openrewrite-for-plugin-modernization/) and volonteer to be mentor for this project if the CNCF organisation is accepted for 2025
Hope this PR is the correct way to submit an idea. 
Regards,
> Add ORAS Java SDK GSoC 2025 mentorship idea

- programs/summerofcode/2025.md
Hello, [Kubewarden](https://www.kubewarden.io/) maintainer here. We would like to include 2 proposals, one to create a Javascript SDK to work on our policies, and one to work in our .NET SDK for policies.
We favour the Javascript SDK one in case there's only 1 proposal per project.
Thanks in advance.
> GsoC 2025: Add Kubewarden proposal 

- programs/summerofcode/2025.md
> GSoC 2025: Meshery

- programs/summerofcode/2025.md
- Description: Lima (<https://lima-vm.io>) is a project that provides Linux virtual machines with a focus on running containers.
Lima supports several VM backends via built-in drivers: `qemu`, `vz` (Apple Virtualization.framework), and `wsl2` (see [`lima/pkg/driverutil/instance.go`](https://github.com/lima-vm/lima/blob/v1.0.5/pkg/driverutil/instance.go#L11-L20)).
The idea for GSoC is to make a plugin subsystem that decouples the built-in VM drivers into separate binaries that communicate with the main Lima binary via some RPC (probably gRPC).
This idea will improve the maintainability of the code base, and also help supporting additional VM backends (e.g., `vfkit` and cloud-based drivers).
- Expected Outcome:
- Design the plugin subsystem and its RPC (probably gRPC)
- Migrate the existing …
> GSoC 2025: add an idea for Lima

- mentees/README.md
- For context, see https://github.com/cncf/techdocs/pull/300
- Uses slack.cncf.io instead of communityinviter.com/apps/cloud-native/cncf
- Other minor copyedit.
/cc @nate-double-u
> Use slack.cncf.io

- programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
This project aims to investigate and implement ideas for replacing/reducing the current KubeStellar Core Helm chart reliance on initContainers for waiting/gathering/processing Kubernetes resources that are used by other containers. For example, KubeFlex Control Planes and their kubeconfigs.
> Add Helm initContainer project to KubeStellar

- programs/lfx-mentorship/2025/02-Jun-Aug/README.md
@miacycle, @sangramrath, @aabidsofi19 @ritzorama
> Meshery LFX 2025 Term 2

- programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Add Karmada project ideas for LFX 2025 term 03.
> Add Karmada project ideas

- programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Add KubeEdge LFX 2025 term3 ideas. PTAL 😄
cc @HongbingZhang @meixiezichuan @wbc6080 @MooreZheng @IcyFeather233 @hsj576 and please give a thumb to confirm this: )
> KubeEdge 2025 LFX terms project ideas

- .github/labeler.yml
- .github/settings.yml
- programs/lfx-mentorship/2026/01-Mar-May/README.md
- programs/lfx-mentorship/2026/01-Mar-May/project_ideas.md
There is a delay between **Project Proposals Open** and **Mentee Applications Open** to give the administrators time to do the LFX Platform Loading & LFX proposal approval.
I've done my best to avoid milestones on major national holidays (not just in the US), so if you notice a conflict in rewiew, please flag it. I've also tried to avoid milestones in major events like KubeCon.
| **Activity**                        | **Date**                                                                 |
|-------------------------------------|--------------------------------------------------------------------------|
| **Project Proposals Open**          | Wednesday, January 7 – Tuesday, January 20, 2026                         |
| **Mentee Applications Open**        | Monday, January 26 – Tuesday, …
> Adding CNCF LFX 2026 Term 1 Schedule
