README.md
Remove the unscoped "DSL" linkerd project
=> Add links to linkerd issues

README.md
Signed-off-by: Eduardo Silva <eduardo@treasure-data.com>
=> Fluentd: update project ideas

README.md
Added the data model project to the Kubernetes project list, formatted like all the rest.
=> Update K8s Projects (Data Model Add)

README.md
Adding issues for k8s projects.
They are not very detailed, but I will use them to track the projects and interact with possible students.
=> Add issues for k8s projects

README.md
Adding some gRPC ideas for summer of code
=> Adding grpc ideas

2017.md, README.md
Ref https://github.com/cncf/soc/issues/22.
/cc @caniszczyk
=> Archive 2017 and start for 2018

README.md
Super early draft, not ready for a merge.
I have added some mentors but not sure if you are up for it though and I am pretty sure I missed some names where people are interested. Please point out and I'll make the changes.
@brancz @superq @brian-brazil @tomwilkie @juliusv @fabxc
=> [WIP] Add Prometheus ideas

README.md
=> Added Paris Pittman as one of the admins for 2018

README.md
=> Add CNCF slack and Kubernetes GSoC page

README.md
/cc @caniszczyk @idvoretskyi @sttts @foxish
=> Add initial list of Kubernetes ideas

README.md
=> Add some CoreDNS ideas

README.md
🎉 🎉 🎉 
/cc @caniszczyk @idvoretskyi
=> Update GSoC 2018 acceptance

README.md
/cc @tomwilkie @brian-brazil as I am adding you as mentors.
=> Add remote read ideas

README.md
This PR adds some GSoC project ideas for Rook, an open source storage orchestrator for cloud-native environments: https://rook.io/
=> add Rook GSoC project ideas

README.md
Mentors have draft a preliminary design doc to help the candidates.
cc @cra
=> Update containerd + kata project with a design doc

README.md
cc @vishh @davidopp @bsalamat @k82cn
=> Update project description for batch scheduling

2019.md
=> GSoC 2019 placeholder added

2019.md, README.md
Ref: https://github.com/cncf/soc/issues/50#issuecomment-453054164
I am receiving lots of questions regarding GSoC 2019 privately (while I'm happy to help, don't really have the time to answer so many DMs :)) so I'd like to mention the gsoc channel on the k8s slack explicitly.
=> Update status for GSoC 2019

PROJECT_IDEA_TEMPLATE.md
Project idea template added for easier consumption.
=> PROJECT_IDEA_TEMPLATE.md added

README.md
=> Timelines and deadlines updated + a few minor updates

README.md
=> Add 2 projects in Prometheus

README.md
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>
=> GSoC Idea: kube-batch + *-operators.

README.md
Here's a proposal for adding new feature to the OpenStack Manila volume provisioner. Hope it's OK like this.
=> Manila provisioner project proposal

README.md
GSoC Ideas: CSI drivers and e2e tests for external Azure cloud provider
@justaugustus @khenidak @andyzhangx
=> GSoC Ideas: CSI drivers and e2e tests for external cloud provider

README.md
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Add OPA IntelliJ plugin proposal

README.md
Add 2 additional projects for the Open Policy Agent
=> Additional OPA projects

README.md
Still few things to clarify.
/cc @floreks
=> Add new proposals related to Kubernetes Dashboard

README.md
Signed-off-by: siddontang <siddontang@gmail.com>
=> GSoC Proposals: Add TiKV projects

README.md
Remove the requirement for Go from the K8s website SASS project.
/cc @lucperkins
=> Remove Golang requirement

2018.md, README.md
Adding virtual kubelet as a project for google summer of code!
=> add vk project

README.md
This PR adds [Yannis Zarkadas](https://github.com/yanniszark) to the list of Rook project ideas.
/cc @yanniszark
=> rook: add yanniszark to Rook mentors

README.md
Ideas from the containerd project maintainers.
Signed-off-by: Phil Estes <estesp@gmail.com>
=> Add containerd GSoC ideas

README.md
Not sure if we can still merge this.
=> Add Falco ideas

README.md
Do not merge yet, sharing with other Cortex maintainers first.
Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>
=> Add Cortex Google Summer of Code Projects

README.md
=> More Prometheus ideas

README.md
/cc @gouthamve @krasi-georgiev
=> More Project: Bulk imports in Prometheus

README.md
/cc @leecalcote @estesp @caniszczyk @idvoretskyi 
Ref: https://github.com/cncf/soc/pull/83#issuecomment-469744869
=> Add note about #gsoc on CNCF slack

README.md
- Prometheus Metrics Exporter
- Performance Analysis and Optimization
- Falco rules profiles for applications and security benchmarks
=> Add additional Falco ideas for GSOC 2019

README.md
Amit Kumar Jaiswal <amitkumarj441@gmail.com>
=> Fix Typo/Recurrence

README.md
Add slack channel/team for Falco.
=> Add communication info for Falco

README.md
ping @gouthamve if he can add more details and possibly add himself as a mentor.
=> Add Postings compression project.

README.md
=> Add Prometheus project to allow index files larger than 64GB.

README.md
Split the prombench project to solve high and low priority issues.
@krasi-georgiev 
Signed-off-by: nikita-mk <nikkikokitkar@gmail.com>
=> Split the Prombench project

README.md
There was a bad merge conflict resolution. This removes the offending line and adds a relevant issue to the proposal.
=> Fix rkt proposal

README.md
One of the OPA community volunteered to mentor this project.
=> Modify mentors for OPA IPTables project

communitybridge/README.md
=> Add multi-tenancy project

communitybridge/README.md
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
=> Add Prometheus projects for communitybridge.

communitybridge/README.md
=> Add m10 project

communitybridge/README.md
=> Added cortex project

communitybridge/README.md
We realized we as a group don't have the bandwidth to support the second project this round. Removing. 
=> Removing second m10 project

communitybridge/README.md
add proposal for kubernetes csi driver
=> doc: add proposal for kubernetes csi driver

communitybridge/README.md
=> fix k8s csi proposal format

communitybridge/README.md
=> Proposed project from Thanos team (:

communitybridge/README.md
update kubernetes CSI driver proposal
cc @idvoretskyi
=> update kubernetes CSI driver proposal

communitybridge/README.md
cc  @juliusv , @boyskila
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
=> Add Prometheus projects for communitybridge. 

README.md
=> The project idea sample added

README.md
:wave: (: 
@idvoretskyi @caniszczyk
=> Added GSoC projects from Thanos Team.

README.md
Signed-off-by: winkyao <golangwink@gmail.com>
Adding GSoC projects from TiKV, PTAL
=> Added GSoC projects from TiKV Team.

README.md
See https://github.com/cortexproject/cortex/issues/2068 for full description of the project.
=> Add GSoC project for Cortex

README.md
Signed-off-by: lowzj <zj3142063@gmail.com>
=> Add GSoC project for Dragonfly

README.md
re-use from the last community bridge. Still actual and I'd be happy to mentor
=> Couple of opentelemetry projects

README.md
/cc @krasi-georgiev @gouthamve
=> Some GSoC project ideas for Prometheus

README.md
=> soc: add in-toto

README.md
=> soc: add TUF

README.md
=> Add GSoC project for KubeEdge

README.md
Adding my name to the mentor list for the Kubernetes Cluster Addon project.
=> Add name to mentor list

README.md
Some urls were pointing to the wrong location
=> fix misc info in tuf and in-toto

README.md
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> soc: Add GSOC projects for OPA

README.md
This PR is to merge the proposal for GSOC 2020
=> Added a new proposal for GSOC 2020

README.md
=> Revert "Added a new proposal for GSOC 2020"

README.md
This PR updates the CoreDNS projects to add Paul (@greenpau) as co-mentor.
=> Update to add co-mentor for CoreDNS projects

README.md
This is in continuation the PR #127 and the required changes have been made.
=> CoreDNS operator :-a GSOC 2020 project proposal

README.md
Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>
=> Add SOC proposal of Virtual Kubelet.

communitybridge/README.md
=> Projects funding pages added

README.md
A proposal for creating better experience for Kubernetes workloads to provision and consume cloud resources.
=> Add kube + cloud resources proposal

README.md
Hello!
I would like to add the following project suggestions for Vitess. 
I have checked with @enisoc and we are both prepared to be mentors.
=> GSoC project suggestions for Vitess

README.md
Please suggest changes if any.
cc: @krasi-georgiev  @codesome @gouthamve 
Signed-off-by: Hrishikesh Barman <plain.hrishikeshbman@gmail.com>
=> GSoC project suggestions : prometheus/test-infra ideas.

README.md
A few suggestions for the [Cloud Native Buildpacks](http://buildpacks.io/).
=> Add Cloud Native Buildpacks project ideas

README.md
A few suggestions for the [OpenEBS](https://github.com/openebs/openebs)
=> add OpenEBS project ideas

README.md
This commit adds Rook project ideas for GSOC.
Signed-off-by: Ashish Ranjan <ashishranjan738@gmail.com>
=> Adds Rook project idea

README.md
=> Change mentor for Flux project

README.md
Add CoreDNS mentor, rephase project and set updated issue.
@rajansandeep should be on this one and not the overall Cluster Addons issue. Yell if that's wrong :)
=> Update Addons/CoreDNS Operator Proposal

README.md
@idvoretskyi to change task is this ok to just change project here? I know some of us were invited already to the GSoC website, but there is nothing about the project there yet.
Can we invite @squat as well? :hugs: 
Thanks! cc @GiedriusS
=> thanos: Changed one GSoC project to more needed / interesting on one.

README.md
Add Michael and Stefan to Flux mentors.
=> Add Michael and Stefan to Flux

README.md
Signed-off-by: Trishank Karthik Kuppusamy <trishank.kuppusamy@datadoghq.com>
=> Add self to TUF SoC

README.md
=> Update multi-tenancy benchmarks

README.md
=> Service Mesh Interface (SMI) Conformance Tool

README.md
=> Add Tobias Guggenmos (@slrtbtfs) as a mentor

README.md
@idvoretskyi 
The email of new mentor is:  yzhang8@gmail.com
=> Update mentor for OAM

communitybridge/README.md
=> Community Bridge H1'2020 deadline extended

communitybridge/cb-mentors-evaluation-form.md
=> CNCF Community Bridge mentors evaluation form added

communitybridge/README.md
=> Community Bridge Q2'2020 timeline proposed

outreachy/README.md
Fixes https://github.com/cncf/mentoring/issues/164
=> Outreachy data added

communitybridge/2019/README.md, communitybridge/2020/q1/README.md
Fixes https://github.com/cncf/mentoring/issues/169
=> Community Bridge historical data added

seasonofdocs/README.md
Signed-off-by: zacharysarah <zach@corleissen.com>
=> [WIP] Update the README for Google Season of Docs 2020

README.md
Fixes https://github.com/cncf/mentoring/issues/97
Signed-off-by: Ihor Dvoretskyi ihor@linux.com
=> GSoC historical data added

communitybridge/2019/README.md
I was also part of the 2019 Community Bridge program with Linkerd & Jaeger!
Adding this as per @idvoretskyi 's request!
Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>
=> Add Distributed Tracing support to Linkerd Mentorship project

README.md
Fixes https://github.com/cncf/mentoring/issues/170
=> Total stats added

communitybridge/2020/q2/project_ideas.md
=> Project Idea

communitybridge/2020/q2/project_ideas.md
Hi,
Following up CNCF end-user group communication, I submitted my proposed idea for OPA
=> added proposed idea

seasonofdocs/README.md
This PR adds project ideas for:
- Improving docs for Kubernetes services 
- Adding more kubectl examples
- Documenting new CLI tools
/assign @caniszczyk 
/cc @idvoretskyi @lucperkins
=> Add more GSoD opportunities for 2020

communitybridge/2020/q2/project_ideas.md
=> Add Thanos projects for CommunityBridge

seasonofdocs/README.md
REF https://github.com/thanos-io/thanos/issues/2041
=> Add Thanos proposal to SoD

communitybridge/2020/q2/project_ideas.md
~Will make it non-WIP once we will finalize the details with the Team! (:~
Ready (:
=> Added last Thanos project for Community Bridge.  🤗

communitybridge/2020/q2/project_ideas.md
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Add OPA CB project

communitybridge/2020/q2/project_ideas.md
* Removed "Running prombench locally" as discussed in the mail with @nikhita 
* Added "Persist retroactive rule reevaluations" as discussed with @codesome 
@bwplotka will you be available to mentor this as @codesome suggested?
Signed-off-by: Hrishikesh Barman <hrishikeshbman@gmail.com>
=> Update Prometheus task list for community-bridge/Q2

communitybridge/2020/q2/project_ideas.md
Fix grammar errors in sentences
=> update project ideas.md

communitybridge/2020/q2/project_ideas.md
Signed-off-by: Eduardo Silva <edsiper@gmail.com>
=> cm: q2: Fluentd: add project idea

communitybridge/2020/q2/project_ideas.md
cc: @bwplotka @csmarchbanks 
Signed-off-by: Callum Styan <callumstyan@gmail.com>
=> add myself as co-mentor for retroactive rules project + add RW project

communitybridge/2020/q2/project_ideas.md
Add CoreDNS Project for CommunityBridge
=> Add CoreDNS Project for CommunityBridge

communitybridge/README.md
CB Communication guidelines updated and moved on top.
=> CB Communication guidelines updated

seasonofdocs/README.md
The focus of this will to centered around updating our developer guide.
=> Add contribex season of docs proposal

.github/settings.yml
Fixes https://github.com/cncf/mentoring/issues/218
=> Added settings.yml

.github/settings.yml
Add write permissions for @zacharysarah 
cc @idvoretskyi @caniszczyk
=> Add write permissions

communitybridge/2020/q2/project_ideas.md
Hi,
There was confusion and looks one project was taken by GSoC already. Let's update with new, fresh and very needed one! :hugs:
=> thanos: Community Bridge Update of Project

communitybridge/2020/q2/README.md, communitybridge/2020/q2/selected_projects.md
=> Q2'2020 participating projects listed

communitybridge/2020/q2/project_ideas.md
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
=> kubevirt: Add project ideas for Q2'2020

communitybridge/2020/q2/README.md
Based on the community demand, we've decided to update some of the deadlines to give folks more flexibility.
=> CB Q2 Deadlines updated

communitybridge/2020/q2/selected_projects.md
Updating CommunityBridge 2020 Q2 list of selected projects.
=> CommunityBridge selected SMI project and mentee

communitybridge/2020/q2/project_ideas.md
I know it's late but some applicants ask for this project to choose from, plus it was suggested by @caniszczyk it's unlikely to have many slots from Summer of Docs this year. (: 
cc @povilasv
=> Added one more Thanos project.

seasonofdocs/README.md
This PR removes Thanos from GSoD per https://github.com/thanos-io/thanos/issues/2041#issuecomment-627279836. 
cc @bwplotka @idvoretskyi
=> Remove Thanos from GSoD

communitybridge/2020/q2/project_ideas.md
=> project_ideas: Fix formatting

communitybridge/2020/q2/selected_projects.md
add TiKV to selected projects' list
=> Add TiKV project to selected projects list

communitybridge/2020/q2/selected_projects.md
Update CoreDNS project for CommunityBridge Program
=> Update CoreDNS project for CommunityBridge Program

communitybridge/2020/q2/selected_projects.md
Signed-off-by: Ashutosh Narkar <anarkar4387@gmail.com>
=> Add mentee for the OPA project for the CommunityBridge Program

communitybridge/2020/q2/selected_projects.md
Signed-off-by: Daniel Belenky <dbelenky@redhat.com>
=> Update selected project for KubeVirt

communitybridge/2020/q2/selected_projects.md
As discussed offline with @idvoretskyi added the selection Thanos & Prometheus projects made so far.
We are still evaluating candidates for one project in Prometheus and one in Thanos! :hugs: Sorry for the lag, but there are many applications and some of them applied just at the last day of application time.
cc @cstyan @squat @kakkoyun @povilasv @yashrsharma44 @thisisobate @jessicagreben :hugs:
=> Updated Community Bridge (Partial) Selection from Thanos and Prometheus

communitybridge/2020/q2/selected_projects.md
=> Add multi-tenancy internship info

communitybridge/2020/q2/selected_projects.md
=> update OpenEBS with additional mentor/mentee

communitybridge/2020/q2/selected_projects.md
cc @cstyan @povilasv @soniasingla @njingco @csmarchbanks 
@idvoretskyi
=> Community Bridge: Final selection for Thanos and Prometheus projects.

communitybridge/2020/q2/selected_projects.md
It looks like markdown programming is hard. :nerd_face:
=> Fixed formatting.

communitybridge/2020/q2/selected_projects.md
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
=> kubevirt: Fix indentation

communitybridge/2020/q2/selected_projects.md
Signed-off-by: Eduardo Silva <edsiper@gmail.com>
=> cb: 2020: q2: Fluentd announcement

seasonofdocs/README.md
/assign @caniszczyk @idvoretskyi
=> Close applications for GSoD 2020

seasonofdocs/README.md
/assign @caniszczyk @idvoretskyi
=> Clarify why we're no longer reviewing submissions

summerofcode/README.md
=> [Envoy] swapping mentors on dist. perf test project

seasonofdocs/README.md
=> Update GSoD timeline to proposal review period

communitybridge/2020/q3-q4/README.md, communitybridge/2020/q3-q4/project_ideas.md, communitybridge/2020/q3-q4/selected_projects.md
=> Community Bridge Q3-Q4 proposed

communitybridge/2020/q3-q4/project_ideas.md
This is our submission for CommunityBridge; in addition to helping Kubernetes, we anticipate that this would help many CNCF and LF projects, and should be considered for an eventual LF service.
=> Add project idea for Kubernetes elections.

communitybridge/2020/q3-q4/project_ideas.md
Signed-off-by: cwen0 <cwenyin0@gmail.com>
=> Add Chaos Mesh project for CommunityBridge

communitybridge/2020/q3-q4/project_ideas.md
=> Add KubeEdge in Community Bridge

communitybridge/2020/q3-q4/project_ideas.md
Support ENUM / SET push down for TiKV Coprocessor. https://github.com/tikv/tikv/issues/8605
This project will be mentored by a previous CommunityBridge project mentee @skyzh who has deep understanding of the corresponding code base now.
=> Update to add TiKV Coprocessor project

communitybridge/2020/q3-q4/project_ideas.md
is it too late? Sorry for delay.
=> Add OpenTelemetry projects

communitybridge/2020/q3-q4/project_ideas.md
Adding a request for Opentelemetry PHP contributors.
=> Adding opentelemetry-php project idea

README.md
=> fix: wrong link for outreachy in readme

communitybridge/2020/q3-q4/project_ideas.md
=> Add Thanos Project ideas

communitybridge/2020/q3-q4/project_ideas.md
=> Service mesh projects for CommunityBridge Q3

communitybridge/2020/q3-q4/project_ideas.md
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
cc @squat
=> Change Thanos mentor for UI project

communitybridge/2020/q3-q4/project_ideas.md
We don't have any project decided yet and plan to do so by the end of the week.
=> Add Prometheus to community bridge q3-q4

communitybridge/2020/q3-q4/project_ideas.md
=> Added Prometheus project issue link.

communitybridge/2020/q3-q4/project_ideas.md
The earlier linked issues has a much bigger scope than the one mentioned in the project. I have opened dedicated issue for them now.
cc @bwplotka
=> Update issue links for Prometheus project

communitybridge/2020/q3-q4/project_ideas.md
Hi, 
Sorry for the late addition, but we would love to add another UI project. We have 20+ good candidates in the React area. right now and we found mentoring resources as well (: 
cc @prmsrswt @kakkoyun @squat
=> thanos: Added Second UI project + Prem as mentor.

communitybridge/2020/q3-q4/selected_projects.md
@SergeyKanzhelev @idvoretskyi - please review.
=> Add OpenTelemetry C++ SDK - ETW exporter project

communitybridge/2020/q3-q4/selected_projects.md
@SergeyKanzhelev @idvoretskyi - please review.
=> Add OpenTelemetry PHP SDK - Exporter project

communitybridge/2020/q3-q4/selected_projects.md
cc @codesome @GayathriVenkatesh
=> prometheus: Selected candidate for Community Bridge Q3-Q4

communitybridge/2020/q3-q4/selected_projects.md
CC @kakkoyun @prmsrswt, @squat, @brancz
Congratulations: @Chans321 @Oghenebrume50 @kunal-kushwaha
=> thanos: Selected Students for Community Bridge Q3-Q4

communitybridge/2020/q3-q4/selected_projects.md
Signed-off-by: Yang Keao <keao.yang@yahoo.com>
=> add Chaos Mesh project

communitybridge/2020/q3-q4/selected_projects.md
Signed-off-by: Song Gao <disxiaofei@163.com>
=> add TiKV rbac project

communitybridge/2020/q3-q4/selected_projects.md
and moved PHP to under the OpenTelemetry title
=> Selection for OpenTelemetry FluentBit project

communitybridge/2020/q3-q4/selected_projects.md
=> Mentee selection for CommunityBridge Q3 service mesh projects

communitybridge/2020/q3-q4/selected_projects.md
Sorry for the delay :)  Add kubeedge to selected projects list
/assign @idvoretskyi 
cc @kevin-wangzefeng
=> Add kubeedge to selected projects list

communitybridge/2020/q3-q4/selected_projects.md
cc @idvoretskyi @jberkus @jdumars @SergeyKanzhelev
=> Adding Kubernetes Community Bridge project

communitybridge/2020/q3-q4/selected_projects.md
Due to the change of work content, Thor-wl and William Wang will take the place of Zhonghu Xu as mentors and guide the project
Signed-off-by: Thor <1187526662@qq.com>
=> Due to the change of work content, update the mentors

communitybridge/README.md
=> Fixed typo in README

lfx-mentorship/2021/01-Spring/project_ideas.md
Creating a Proposal for an OpenTelemetry PHP project for the spring 2021 season.
=> Spring 2021 OpenTelemetry PHP

lfx-mentorship/2021/01-Spring/project_ideas.md
Creating proposals for the TiKV project for 2021 spring.
=> Add TiKV 2021 spring proposal

lfx-mentorship/2021/01-Spring/project_ideas.md
=> Add SIG Usability project and fix a typo

lfx-mentorship/2021/01-Spring/project_ideas.md
Signed-off-by: xiang <xiang13225080@163.com>
=> format project idea for Chaos Mesh

lfx-mentorship/2021/01-Spring/project_ideas.md
/cc @kevin-wangzefeng @GsssC
/assign @idvoretskyi
=> Add project ideas for KubeEdge

lfx-mentorship/2021/01-Spring/project_ideas.md
We would like to add some issues/mentorship opportunities for tremor. Feel free to reach out of there are any issues / questions :)
=> Add tremor opportunities 

lfx-mentorship/2021/01-Spring/project_ideas.md
Signed-off-by: STRRL <str_ruiling@outlook.com>
Another proposal about ChaosMesh, enriching AWS chaos:
- enriching e2e test cases
- more chaos about AWS service failure
=> Propose another ChaosMesh project 

lfx-mentorship/2021/01-Spring/project_ideas.md
cc @squat @kakkoyun @prmsrswt @yashrsharma44
=> Added Thanos Spring 2021 LFX Projects

lfx-mentorship/2021/01-Spring/project_ideas.md
add kubeadm project idea for Spring 2021.
=> project_ideas.md: add kubeadm project idea

lfx-mentorship/2021/01-Spring/project_ideas.md
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> add code-organization project idea

lfx-mentorship/2021/01-Spring/project_ideas.md
=> Propose Crossplane projects

lfx-mentorship/2021/01-Spring/project_ideas.md
Signed-off-by: Thor-wl <1187526662@qq.com>
=> add 2021 Q1 community bridge project ideas for Volcano

lfx-mentorship/2021/01-Spring/project_ideas.md
Signed-off-by: Luke Hinds <lhinds@redhat.com>
=> Propose Project Rekor

lfx-mentorship/2021/01-Spring/project_ideas.md
Signed-off-by: ksatchit <karthik.s@mayadata.io>
=> add litmuschaos project idea for Q1-2021

lfx-mentorship/2021/01-Spring/project_ideas.md
This commit adds the SPIRE project to the Spring 2021 LFX Mentorship Program.
Please let me know if there's anything else I need to do. Thanks for your help!
Signed-off-by: Evan Gilman <egilman@vmware.com>
=> Add SPIRE Project to Spring 2021 LFX Mentorship Program

summerofcode/2021.md
adding a project idea for Keptn
=> adding Keptn project

lfx-mentorship/2021/01-Spring/project_ideas.md
=> LFX Spring 21: Open Service Mesh - WASM Support

lfx-mentorship/2021/01-Spring/project_ideas.md
=> LFX Spring 21: Envoy - Nighthawk

summerofcode/2021.md
Signed-off-by: Raj Babu Das <raj@chaosnative.com>
=> Adding litmuschaos for GSoC 2021

summerofcode/2021.md
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
=> Add GSoC 2021 entry for OpenEBS

summerofcode/2021.md
cc: @bwplotka I would love a review to make sure the description seems reasonable.
=> Add proposal for Prometheus configurable retention

summerofcode/2021.md
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Add Prometheus OpenAPI

seasonofdocs/README.md, seasonofdocs/previous-years/2020/README.md
=> Update season of docs for GSoD 2021

summerofcode/2021.md
=> Added 2 projects from Thanos

summerofcode/2021.md
Kindly ping @idvoretskyi for approval.
=> Add crossplane oam app proposal

summerofcode/2021.md
=> Fix the wrong indentation.

seasonofdocs/README.md
=> Add project proposal for GSoD 2021

summerofcode/2021.md
This project was completed in LFX mentorship
=> Remove CNB project

summerofcode/2021.md
Adds a description of a project for in-toto.
cc @SantiagoTorres @lukpueh
=> Add project: in-toto-rs for rebuilderd

summerofcode/2021.md
xref: https://github.com/jetstack/cert-manager/issues/3783
=> Add a `kubectl cert-manager install` proposal

summerofcode/2021.md
=> Add Cloud Native Buildpacks - Jenkins Plugin

summerofcode/2021.md
xref: https://github.com/kubernetes-sigs/cluster-addons/issues/100
=> add sig-cluster-addons project for 2021

summerofcode/2021.md
Add hashed bin delegations for go-tuf.
=> Add project for TUF

summerofcode/2021.md
Adds another task for in-toto.
cc @SantiagoTorres
=> Add project: signature wrapper task for in-toto

summerofcode/2021.md
I'd like to add myself as a mentor for the in-toto signing-spec project. Can I also be added to the GSOC portal to review in-toto proposals?
Thanks!
=> in-toto: Add Aditya as a mentor

lfx-mentorship/2021/02-Summer/project_ideas.md
=> Add Racklet to the list of project ideas

lfx-mentorship/2021/02-Summer/project_ideas.md
=> Add tremor project ideas for lfx mentorship summer 2021.

lfx-mentorship/2021/02-Summer/project_ideas.md
This PR adds a project idea for Vitess for LFX 2021 summer term.
=> Add project idea for Vitess

lfx-mentorship/2021/02-Summer/project_ideas.md
=> Add kubeedge to project ideas

lfx-mentorship/2021/02-Summer/project_ideas.md
=> Proposed Thanos projects.

lfx-mentorship/2021/02-Summer/project_ideas.md
=> add image scan adapter

lfx-mentorship/2021/02-Summer/project_ideas.md
=> LFX Q2-Summer: Meshery and SMI projects

lfx-mentorship/2021/02-Summer/project_ideas.md
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> Adding a new project CAPG

lfx-mentorship/2021/03-Fall/project_ideas.md
=> add Policy-WG KubeArmor support for PolicyReport CRD

lfx-mentorship/2021/03-Fall/project_ideas.md
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> Two project proposals related to kubernetes

lfx-mentorship/2021/03-Fall/project_ideas.md
This PR adds the proposals from Vitess for LFX fall term 2021
=> Adds proposals from Vitess for LFX fall term 2021

lfx-mentorship/2021/03-Fall/project_ideas.md
Signed-off-by: Shuting Zhao <shutting06@gmail.com>
=> Add proposal for Kyverno tests

lfx-mentorship/2021/03-Fall/project_ideas.md
Signed-off-by: STRRL <str_ruiling@outlook.com>
- Description: Observability is very important for each application, we want to monitor more things of Chaos Mesh components, enrich the metrics for both logic patterns and performance data. We want to let users could watch the status of Chaos Mesh on grafana dashboard, and developers could using time-series metrics for debugging and profiling.
- Recommended Skills: golang, prometheus, grafana
- Mentor(s): [@ZhiqiangZhou](https://github.com/strrl)
- Issue: <https://github.com/chaos-mesh/chaos-mesh/issues/2198>
=> Add proposal for chaos mesh

lfx-mentorship/2021/03-Fall/project_ideas.md
=> Add WasmEdge project proposals

lfx-mentorship/2021/03-Fall/project_ideas.md
=> add Kyverno security and minor update for other Kyverno projects

lfx-mentorship/2021/03-Fall/project_ideas.md
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
Adding @gdsoumya as a mentor for litmuschaos project
=> Adding mentor for litmuschaos project

lfx-mentorship/2021/03-Fall/project_ideas.md
=> Add Thanos project idea

lfx-mentorship/2021/03-Fall/project_ideas.md
This commit proposes a new project for Thanos.
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>
cc @kakkoyun @GiedriusS @idvoretskyi
=> fall 2021: add Thanos protobuf project

lfx-mentorship/2021/03-Fall/project_ideas.md
Add project for upgrade/downgrade testing to LFX fall term
=> Add project for upgrade/downgrade testing to LFX fall term

lfx-mentorship/2021/03-Fall/project_ideas.md
=> add mentor

lfx-mentorship/2021/03-Fall/project_ideas.md
/cc @celestehorgan, @jberkus, @spzala, @chalin
Contributes to https://github.com/cncf/techdocs/issues/40
Closes https://github.com/cncf/techdocs/issues/66
=> Add etcd docs project idea

lfx-mentorship/2021/03-Fall/project_ideas.md
This pr adds a new thanos project for the LFX Fall term.
=> Add thanos project about compactor metrics

lfx-mentorship/2021/03-Fall/project_ideas.md
=> Addition of Meshery to LFX Fall '21

lfx-mentorship/2021/03-Fall/project_ideas.md
=> Addition of SMP to LFX Fall '21

README.md, lfx-mentorship/2020/q3-q4/README.md, lfx-mentorship/2021/01-Spring/README.md, lfx-mentorship/2021/02-Summer/README.md, lfx-mentorship/README.md
=> Fix Cycle Inconsistencies

.github/settings.yml
=> label update: community bridge -> lfx mentorship

lfx-mentorship/2022/01-Spring/project_ideas.md
- Description: [LitmusChaos]("https://litmuschaos.io") is an open source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way. This project aims to develop new commands/features for litmusctl along with integration tests for it.
- Recommended Skills: Golang, Kubernetes, CLI
- Mentor(s): Raj Babu Das (@rajdas98), Sarthak Jain (@SarthakJain26), Saranya Jena (@Saranya-jena)
- Upstream Issue (URL): https://github.com/litmuschaos/litmus/issues/3440
=> Add LitmusChaos to LFX Mentorship Q1-2022

lfx-mentorship/2022/01-Spring/project_ideas.md
Project ideas for [kubearmor](https://github.com/kubearmor/KubeArmor/) as part of LFX Mentorship program.
CC: @nam-jaehyun, @daemon1024
Signed-off-by: Rahul Jadhav <r@accuknox.com>
=> Add Kubearmor to LFX Mentorship Q1-2022

lfx-mentorship/2022/01-Spring/project_ideas.md
- Description: [KubeVela](https://github.com/oam-dev/kubevela) is a modern application delivery platform based on Kubernetes. It is currently a CNCF Sandbox project. KubeVela supports managing application delivery in multi-clusters. One of the basic problem is to validate the health status of managed clusters. Besides, it is also useful to integrate other metrics like CPU core usage or number of available graphical cards. This project aims to establish a mechanism to support these features.
- Recommended Skills: golang, k8s
- Mentor(s): Jianbo Sun (@wonderflow), Da Yin (@somefive)
- Upstream Issue (URL): https://github.com/oam-dev/kubevela/issues/3177
- Description: [KubeVela](https://github.com/oam-dev/kubevela) is a modern application delivery platform based on Kubernetes. It is …
=> Add KubeVela to LFX Mentorship Q1-2022

lfx-mentorship/2022/01-Spring/project_ideas.md
Project ideas for [Karmada](https://github.com/karmada-io/karmada) as part of LFX Mentorship program.
cc @kevin-wangzefeng
=> CNCF mentorship project ideas for Karmada

lfx-mentorship/2022/01-Spring/project_ideas.md
Signed-off-by: Charly Molter <charly.molter@konghq.com>
=> Add projects for Kuma for Spring 2022 LFX

lfx-mentorship/2022/01-Spring/project_ideas.md
Signed-off-by: hydai <hydai@secondstate.io>
=> Add WasmEdge lfx 2022 spring project ideas

lfx-mentorship/2022/01-Spring/project_ideas.md
Sorry @idvoretskyi, just scraping in before deadline on this one.
@nate-double-u Here's the project request we discussed.
Signed-off-by: Nick Young <ynick@vmware.com>
=> Add Gateway API to LFX Mentorship Q1-2022

lfx-mentorship/2022/01-Spring/project_ideas.md
This PR adds the proposal for the parser project in Vitess for LFX spring term, 2022.
=> Add Vitess LFX Spring term 2022 Proposal

lfx-mentorship/2022/01-Spring/project_ideas.md
Proposed project to implement last season's audit recommendations for improving Elekto security.
=> Add proposed Elekto internship

lfx-mentorship/2022/01-Spring/project_ideas.md
This PR adds a project for automating AMI build/test/publish workflow for Cluster API Provider AWS, which is a Kubernetes SIG Cluster Lifecycle sub-project, to LFX spring term.
=> Add Cluster API Provider AWS proposal to LFX Mentorship Spring 2022

summerofcode/2022.md, summerofcode/README.md
=> 2022 GSoC info added

lfx-mentorship/2022/01-Spring/project_ideas.md
=> Add Thanos project

lfx-mentorship/2022/01-Spring/project_ideas.md
Already discussed with @dims. We'll add a link to an issue with the complete task last once the maintainers repo is migrated over.
cc @palnabarun @mrbobbytables @idvoretskyi
=> lfx-spring-2022: k8s: add project for maintainers automation

lfx-mentorship/2022/01-Spring/project_ideas.md
OpenTelemetry PHP Spring 2022 PHP mentorship
=> OpenTelemetry PHP Spring 2022 PHP mentorship

lfx-mentorship/2022/01-Spring/project_ideas.md
=> Add a subproject of KubeVela: Terraform Controller

summerofcode/2022.md
Empower KubeVela to support more Cloud providers and Cloud resources.
=> KubeVela: Support more clouds

lfx-mentorship/2022/01-Spring/project_ideas.md
Add proposed project for adding new protocol tracing support for new protocols to Pixie.
=> Add Pixie protocol parser project

lfx-mentorship/2022/01-Spring/project_ideas.md
=> LFX Spring 2022 Service Mesh Projects

summerofcode/2022.md
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> Add GSoC project ideas for Argo

summerofcode/2022.md
* observability and policy discovery support
* supporting kubearmor on ARM platforms
Signed-off-by: Rahul Jadhav <r@accuknox.com>
=> GSOC: Kubearmor project ideas

summerofcode/2022.md
=> Add CoreDNS project for GSoC

summerofcode/2022.md
This PR added GSoC ideas of Karmada project
=> GSoC: Karmada project ideas

summerofcode/2022.md
=> Kyverno gsoc 22

summerofcode/2022.md
=> Add WasmEdge GSoC project ideas

summerofcode/2022.md
Add project ideas for KubeEdge.
=> Add KubeEdge to GSOC 2022

summerofcode/2022.md
- Add CAPG to GSOC 2022
cc @dims
=> Add CAPG to GSOC 2022

summerofcode/2022.md
This PR adds cert-manager's project idea for Google Summer of Code 2022.
Please let us know if any additional description or information is needed.
Signed-off-by: irbekrm <irbekrm@gmail.com>
=> Adds cert-manager Google Summer of Code mentorship proposal

summerofcode/2022.md
=> GSOC: Add TUF projects

summerofcode/2022.md
=> GSOC: Add in-toto projects

summerofcode/2022.md
* Remove duplicate DSSE project
* Add Jenkins plugin project
The DSSE proposal was added in both #499 and #504. Apologies for the confusion!
=> Fix in-toto projects

lfx-mentorship/2022/01-Spring/README.md, summerofcode/2022.md
Also added mentor to LFX project.
cc @wiardvanrij @GiedriusS @onprem @squat @matej-g
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> GSoC: Added Thanos project.

summerofcode/2022.md
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
=> Add another thanos gsoc project

summerofcode/2022.md
=> GSoC 2022 - Meshery and Service Mesh Performance

summerofcode/2022.md
Add another project idea for Chaos Mesh GSoC 2022.
=> add another chaos mesh gsoc project

summerofcode/2022.md
Based on additional requirements mentioned in https://github.com/cncf/mentoring/pull/482#issuecomment-1051311616.
Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>
=> Update Argo GSoC 2022 project ideas to be more descriptive

summerofcode/2022.md
This addressed the TUF tasks in #523.
=> Add outcomes, size, and difficulty for TUF projects

summerofcode/2022.md
This PR update CoreDNS project for more details. See #491
/cc @nate-double-u @greenpau
=> Update CoreDNS project for more details.

summerofcode/2022.md
- Add in-toto-rs + rebuilderd task
- Update old tasks with changes as per new GSOC guidelines
=> Multiple in-toto changes

.github/labeler.yml, .github/workflows/label.yml
Automating some of the boring stuff.
I'm not sure if i need to create a `secrets.GITHUB_TOKEN` or if that's automatic on repo creation.
=> setting up automatic labelling for PRs

.github/labeler.yml
=> updating labeler yml

.github/labeler.yml
=> updating labeler yml to remove "any" and "all"

summerofcode/2022.md
Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>
=> Add project details for Pixie GSoC projects

summerofcode/2022.md
Update for #512
Signed-off-by: Juan Bustamante <jbustamante@vmware.com>
=> Added detailed project descriptions for Buildpack PoC

summerofcode/2022.md
Added detailed project descriptions for KubeArmor.
ref #523 
/cc @nate-double-u, @daemon1024
Signed-off-by: Rahul Jadhav <nyrahul@gmail.com>
=> KubeArmor detailed project description for GSoC

summerofcode/2022.md
Add more details as requested.
=> Update GSoC Project: Buildpacks - Standardize Cache Flag options

summerofcode/2022.md
=> details for Kyverno projects

summerofcode/2022.md
Updated project information per request.
=> Update project `Extend more Cloud providers and Cloud resources`

summerofcode/2022.md
ref https://github.com/cncf/mentoring/pull/479#issuecomment-1051311253 and #523 
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>
=>  Added detailed project descriptions for Chaos Mesh single binary deployment

summerofcode/2022.md
Fixed the WasmEdge part in #523
=> update wasmedge 2022 gsoc

summerofcode/2022.md
This PR updated Karmada proposals ideals.
=> [GSoC]Update Karmada project for more details

summerofcode/2022.md
Signed-off-by: Matej Gera <matejgera@gmail.com>
Filling in the missing information.
cc @bwplotka, @yeya24, @onprem, @squat
=> GSoC 2022: Update Thanos project information to conform with the project guidance

summerofcode/2022.md
This PR will Update details for litmuschaos gsoc'22 according to https://github.com/cncf/mentoring/issues/523.
Signed-off-by: Jonsy13 <vedant.shrotria@chaosnative.com>
=> Updated details for litmuschaos gsoc'22

summerofcode/2022.md
=> reorganizing projects - adding Kubernetes section

summerofcode/2022.md
This PR updates details for Meshery and Service-Mesh-Performance gsoc'22 according to https://github.com/cncf/mentoring/issues/523.
=> Meshery and Service Mesh Performance details update

summerofcode/2022.md
Signed-off-by: Rashmi Gottipati <chowdary.grashmi@gmail.com>
=> Update kubebuilder project information to conform with the project guidelines

summerofcode/2022.md
Updating default level of effort and difficulty. Adding Expected Outcomes. Updating descriptions where needed.
These do not have to be the final values, but I want every project to have a complete entry.
=> Updating GSoC 2022 projects with defaults and adding expected outcomes

.github/settings.yml
=> adding project labels

summerofcode/2022.md
https://github.com/cncf/mentoring/blob/main/summerofcode/2022.md#cluster-api-provider-gcp
cc @cpanato @dims
=> Add @richardcase and @pydctw as mentors for CAPG GSoC project

lfx-mentorship/2022/01-Spring/README.md, lfx-mentorship/2022/01-Spring/project_ideas.md, lfx-mentorship/2022/02-Summer/README.md, lfx-mentorship/2022/02-Summer/project_ideas.md
updating 2022 spring, setting up 2022 summer
=> LFX 02-2022 Summer setup.

lfx-mentorship/2022/02-Summer/project_ideas.md
Signed-off-by: Ramona Łuczkiewicz <ja@agares.info>
Signed-off-by: Darach Ennis <darach@gmail.com>
Signed-off-by: Heinz N. Gies <heinz@licenser.net>
Signed-off-by: Matthias Wahl <matthiaswahl@m7w3.de>
=> Add tremor mentorships for Summer 2022

lfx-mentorship/2022/02-Summer/project_ideas.md
Signed-off-by: Thor-wl <13164644535@163.com>
=> add ideas of Volcano project for community bridge 2022 Q2

lfx-mentorship/2022/02-Summer/project_ideas.md
Project ideas for [Karmada](https://github.com/karmada-io/karmada) as part of LFX Mentorship program.
=> add ideas of Karmada project for lfx summer 2022

lfx-mentorship/2022/02-Summer/project_ideas.md
Project ideas for [kubearmor](https://github.com/kubearmor/KubeArmor/) as part of LFX Mentorship summer program.
cc: @nyrahul @daemon1024
=> CNCF mentorship project ideas for KubeArmor

lfx-mentorship/2022/02-Summer/project_ideas.md
Dashboard Development Project idea of [Karmada](https://github.com/karmada-io/karmada) as part of LFX Mentorship program.
cc: @RainbowMango
=> Added Dashboard Development project idea of the Karmada for lfx summer 2022

lfx-mentorship/2022/02-Summer/project_ideas.md
Signed-off-by: ShutingZhao <shuting@nirmata.com>
=> Add kyverno project ideas

lfx-mentorship/2022/02-Summer/project_ideas.md
=> Add WasmEdge lfx 2022 summer

lfx-mentorship/2022/02-Summer/project_ideas.md
Signed-off-by: FeynmanZhou <feynman@kubesphere.io>
Sorry for the late submission, I hope it could be accepted. 
/cc @nate-double-u
=> add an OpenFunction project to LFX mentoring summer

lfx-mentorship/2022/02-Summer/project_ideas.md
Hi @nate-double-u ,
I just added OpenELB projects to LFX mentoring summer. OpenELB is a young project, we hope this program could help us to involve more contributors to engage with it. Thanks for your help.
=> Add OpenELB projects to LFX mentoring summer

lfx-mentorship/2022/02-Summer/README.md, lfx-mentorship/2022/02-Summer/project_ideas.md
=> LFX Mentorship '22 summer: moving projects from proposed to accepted

lfx-mentorship/2022/02-Summer/project_ideas.md
Proposed LFX Summer 2022 Projects for Meshery and SMP projects.
=> SMP and Meshery Projects for Summer 2022

lfx-mentorship/2022/02-Summer/README.md, lfx-mentorship/2022/02-Summer/project_ideas.md
Adding Meshery & Service Mesh Performance projects to LFX Mentoring accepted projects (2022-summer)
=> Adding Meshery & Service Mesh Performance projects to LFX '22 Summer

lfx-mentorship/2022/02-Summer/README.md
Added  Edits Broken URL for Devfile
=> Fixed Broken URL for Devfile

lfx-mentorship/README.md
=> Removed duplicate `use the`

lfx-mentorship/2022/02-Summer/project_ideas.md
This PR adds the Vitess's proposed project for the LFX summer term 2022.
=> Adds vitess's proposed project for Summer term LFX 2022

lfx-mentorship/2022/02-Summer/README.md, lfx-mentorship/2022/02-Summer/project_ideas.md
=> LFX 2022 Summer: moving Vitess project from project ideas to readme. 

lfx-mentorship/2022/03-Sept-Nov/README.md
Extending 03-Sept-Nov project proposal date range by two days due to missed announcement.
=> Updating 03-Sept-Nov project proposal date range

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Signed-off-by: Bill Mulligan <billmulligan516@gmail.com>
=> Add Cilium SBOM project idea

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
This PR adds Vitess's proposed project for the LFX winter term 2022.
=> Adds vitess's proposed project for Winter term LFX 2022

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Signed-off-by: Bill Mulligan <bmulligan@linuxfoundation.org>
=> Add Github issue to Cilium project idea

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Signed-off-by: YiYing He <yiying@secondstate.io>
=> Add WasmEdge lfx 2022 fall

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Adds a list of Kyverno proposed projects to the LFX Fall 2022 mentorship program.
=> Add Kyverno proposed projects

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Project ideas for [Karmada](https://github.com/karmada-io/karmada) as part of the LFX Mentorship program.
=> add ideas of Karmada project for lfx Sept-Nov 2022

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Hey! Here's a project proposal for Vitess. Cheers!
=> Add Vitess Evaluation Engine to Proposals

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Signed-off-by: YiYing He <yiying@secondstate.io>
=> Update WasmEdge lfx 2022 fall

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
=> Add project proposal for Thanos

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Sorry that this is the last one, must be :-)
=> Update the last mentership of WasmEdge lfx 2022 fall

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Added project for Thanos.

lfx-mentorship/2022/03-Sept-Nov/project_ideas.md
=> [LFX Fall] Projects: TAG Network and Observability, SMP, Meshery

lfx-mentorship/2022/03-Sept-Nov/README.md
Signed-off-by: Chip Zoller <chipzoller@gmail.com>
=> Replaces issue number of a Kyverno project

lfx-mentorship/2022/03-Sept-Nov/README.md
Fixes (for the last time) the [Implement new custom JMESPath filters](https://mentorship.lfx.linuxfoundation.org/project/bb0ff695-3d54-4ce2-b93c-3ab92842b3ee) mentorship listing.
=> Fix Kyverno mentorship description

lfx-mentorship/2022/03-Sept-Nov/README.md
Updated the project description to remove incorrect information about the project code.
Signed-off-by: Nikhil Ladha <nikhilladha1999@gmail.com>
=> Updated issue description of meshery project

README.md
**Draft** Do not merge till all results are in.
=> adding LFX Summer 2022 to README

.github/settings.yml, lfx-mentorship/2022/02-Summer/README.md, lfx-mentorship/2022/03-Sept-Nov/README.md, lfx-mentorship/2023/01-March-May/README.md, lfx-mentorship/2023/01-March-May/project_ideas.md
First pass at dates for LFX mentorship term 1, 2023
=> setting up CNCF LFX Mentorship Term 01: March-May

TAGCS-Mentoring-WG/README.md
missed a dot on a link to the meeting minutes.
Signed-off-by: Nate W. <natew@cncf.io>
=> Updating mentoring wg readme

TAGCS-Mentoring-WG/2022-meeting-minutes.md
Mentoring WG meeting minutes for 2022-10-25
=> 2022-10-25-meeting

.github/settings.yml
Signed-off-by: Riaan Kleinhans <61125752+Riaankl@users.noreply.github.com>
=> Add Riaan Kleinhans as maintainer

TAGCS-Mentoring-WG/2022-meeting-minutes.md
2022-11-08 mentoring WG meeting minutes.
=> 2022-11-08-meeting

README.md, lfx-mentorship/2022/03-Sept-Nov/README.md
* updating 2022 stats
* adding LFX Mentoring 2022 term 3: Sept-Nov
=> End of term / end of year status updates

TAGCS-Mentoring-WG/2022-meeting-minutes.md
Mentoring WG meeting minutes for Dec 13, 2022
=> 2022-12-13 working group meeting

PROJECT_IDEA_TEMPLATE.md, lfx-mentorship/2023/01-Mar-May/project_ideas.md
=> updating LFX Mentorship templates

.github/settings.yml, PROJECT_IDEA_TEMPLATE.md, mentoring-wg/2022-meeting-minutes.md, mentoring-wg/2023-meeting-minutes.md, programs/archive/README.md, programs/lfx-mentorship/2022/03-Sept-Nov/README.md, programs/lfx-mentorship/2023/01-Mar-May/project_ideas.md, programs/lfx-mentorship/README.md
This PR brings v2 up to date with any changes that have been made in main
=> merging main into v2

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Adds a project idea for LFX Spring 2023 for Cluster API Provider GCP
/cc @cpanato
=> docs: added capg project idea

lfx-mentorship/2023/01-Mar-May/project_ideas.md
This pr add KubeVela's proposed project for the LFX 2023 01-May-Mar.
=> Add KubeVela making addons proposal for LFX 2023 01-May-Mar

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Proposal for LFX 2023 internship.
Related Vitess issue: https://github.com/vitessio/vitess/issues/12136
=> LFX internship proposal: Vitess VReplication testing framework 

README.md
Update links in the repo to relative links and expand readme content
Also remove Cross from the readme [Issue#738](https://github.com/cncf/mentoring/issues/738#issuecomment-1397671603)
Signed-off-by: Riaan Kleinhans <61125752+Riaankl@users.noreply.github.com>
=> Create relative links and expand readme content

summerofcode/2023.md, summerofcode/README.md
I'll add a timeline section in a followup PR
=> Adding GSoC 2023

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: Bill Mulligan <bmulligan@linuxfoundation.org>
=> Add Cilium project idea

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Add KubeVela SDK auto-generation proposal for LFX 2023.
Ref: https://github.com/kubevela/kubevela/issues/5365
=> Feat: add kubevela sdk auto-generation proposal

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Add KubeVela auto-generator proposal for LFX 2023.
Ref: kubevela/kubevela#5364
=> Feat: add KubeVela auto-generator  proposal for LFX 2023

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: Zhen Zhang <furykerry@gmail.com>
=> Feat: add proposal for LFX 2023

lfx-mentorship/2023/01-Mar-May/project_ideas.md
This PR adds Vitess's proposed parser project for the LFX summer term 2023.
=> Adds Vitess's proposed project for LFX 2023 term 01-Mar-May

lfx-mentorship/2023/01-Mar-May/project_ideas.md
- Description:  [LitmusChaos](https://litmuschaos.io) is an open-source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way. This project aims to improve the code quality of the golang components of litmus chaos and refactor the codebase for adding the unit test cases. 
- Expected Outcome: This will help the project to improve code quality, enhance the unit test suite, and identification of weaknesses
- Recommended Skills: Golang, Kubernetes
- Mentor: Amit Kumar Das (@amityt, amit.das@harness.io)  Sayan Mondal (@S-ayanide, sayan.mondal@harness.io)
- Upstream Issue: https://github.com/litmuschaos/litmus/issues/3892
=> Adding LitmusChaos to LFX-23-Q1

lfx-mentorship/2022/03-Sept-Nov/README.md, lfx-mentorship/2023/01-Mar-May/project_ideas.md
Adds GitHub handles and emails for Kyverno project proposals.
=> Add handles and emails

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: Ben Ye <benye@amazon.com>
cc @alanprot @alvinlin123 @friedrichg
=> Add project ideas for Cortex

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Adds TestGrid, a kubernetes-serving open-source project, as an LFX Mentoring proposal.
=> Add TestGrid UI to LFX Mentorship Ideas for 2023

lfx-mentorship/2023/01-Mar-May/project_ideas.md
A couple of updates to the CAPA/CAPG prject ideas:
- Added email addresses for CAPG mentors
- Add @Ankitasw as a mentor on the CAPA project
- Added email addresses for CAPA mentors
=> docs: updated CAPA/CAPG mentor details

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
=> Add project ideas for Harbor

lfx-mentorship/2023/01-Mar-May/project_ideas.md
Added mentorship proposal for CNCF Improvement mentorship 
Signed-off-by: Andrea Velazquez <calexicorama@gmail.com>
=> LFX - CNCF Landscape UX UI improvement

lfx-mentorship/2023/01-Mar-May/README.md, lfx-mentorship/2023/01-Mar-May/project_ideas.md
Draft till approved by LFX.
* Adding Harbor projects
=> Moving proposals to accepted (LFX Mentorship 2023 term 1: March - May)

summerofcode/2023.md
=> GSOC: Jaeger

summerofcode/2023.md
/cc @yurishkuro
Updating formatting to match template.
=> updating Jaeger idea formating (GSoC 2023 idea).

.github/settings.yml
=> adding hold label

lfx-mentorship/2023/01-Mar-May/README.md
=> LFX Spring 2023: meshery, tag-network, smp

lfx-mentorship/2023/01-Mar-May/README.md
Moving timeline, project instructions, application instructions above table of contents to make it easier for folks to find key info on first visit.
=> Reformatting LFX 2023 01-Mar-May README for easier access to key info

summerofcode/2023.md
=> Add WasmEdge GSoC 2023 project idea

summerofcode/2023.md
Signed-off-by: ilixiaocui <ilixiaocui@163.com>
=> GSOC: Add three ideas for Curve

summerofcode/2023.md
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> GSOC: add OpenFeature project ideas for GSoC 23

summerofcode/2023.md
Mention high-level technical tasks based on feedback from @aliok in [this comment](https://github.com/cncf/mentoring/pull/834#pullrequestreview-1298490303).
=> GSoC: extend OpenFeature project description

summerofcode/2023.md
=> GSoC: Add Proposal for KubeBuilder - Helper to upgrade projects

TAGCS-Mentoring-WG/2023-meeting-minutes.md
Sorry I'm a bit late pushing these to GitHub.
=> 2023-02-14 Meeting Minutes

summerofcode/2023.md
cc @mheon @saschagrunert @lenicatko
=> GSoC 2023: add CRI-O proposals

summerofcode/2023.md
* alphabetizing
* adding table of contents
=> Organizing GSoC 2023 ideas list

summerofcode/2023.md
cc @nate-double-u @TheSpiritXIII @macxamin
=> Proposed GSoC project from Prometheus

summerofcode/2023.md
=> Add task for TUF content addressable support

summerofcode/2023.md
I wrote up a more-detailed issue, rather than reusing a smaller existing issue.
=> Update issue link for Knative NetworkPolicy support project

summerofcode/2023.md
- Add project ideas for KubeArmor for GSoC 2023
=> add kubearmor projects for gsoc 2023

summerofcode/2023.md
Adding project ideas for Falco for GSoC 2023.
=> update(summerofcode/2023.md): add falco projects

.github/labeler.yml, .github/settings.yml, .github/workflows/prlabeler.yml, mentoring-wg/2023-meeting-minutes.md, programs/lfx-mentorship/2023/01-Mar-May/README.md, programs/lfx-mentorship/2023/02-Jun-Aug/README.md, programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md, programs/lfx-mentorship/2023/03-Sep-Nov/README.md, programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md, programs/lfx-mentorship/README.md, programs/seasonofdocs/README.md, programs/summerofcode/README.md, seasonofdocs/previous-years/2021/README.md
Merging `main` into `v2` to keep in sync.
=> Merged main v2 2023-03-14

summerofcode/2023.md
Would like to add this proposal to summerofcode 2023.
=> GSoC: Add Proposal for KubeBuilder - Phase 2 Plugins API 

summerofcode/README.md
- Update GSoC admins list with the 4 people I saw listed on GSoC system
=> Update GSoC admins list

programs/summerofcode/2023.md, programs/summerofcode/README.md
Merging main into v2 to keep in sync.
=> Merged main v2 (2023-03-28)

programs/summerofcode/2023.md, programs/summerofcode/README.md
Reverts cncf/mentoring#900
I used "rebase and merge" function, which doesn't help with resolving the conflicts
=> Revert "Merged main v2 (2023-03-28)"

mentoring-wg/2023-meeting-minutes.md, programs/summerofcode/2023.md
Merge main into v2 to keep in sync
This PR should be merged with a merge commit.
=> Merged main v2 2023-03-30

summerofcode/2023.md
This PR adds CoreDNS DoQ/DoH3 support as a proposal for sutdent consideration.
=> Add CoreDNS proposals

summerofcode/2023.md
Add hyperlinks for Meshery projects at the top section of the page and also corrected some other links
=> Add hyperlinks for Meshery projects

programs/summerofcode/2023.md
Merging main into v2 to keep in sync.
=> Merged main  -> v2 (2023-04-05)

mentoring-wg/gsoc-org-admin-guide.md
Update GSoC admin guide with example announcements
=> Update GSoC admin guide with example announcements

summerofcode/2023.md
Added a co-mentor to the Strimzi MQTT to Kafka related proposal.
=> Updated Strimzi proposal co-mentor

programs/summerofcode/2023.md
Merging main into v2 to keep in sync.
This pr should be merged with a merge commit.
=> Merged main -> v2 (2023-04-10)

mentees/README.md, mentors/README.md
Calling out draft pages in v2, as per PR feedback https://github.com/cncf/mentoring/pull/899#discussion_r1161028049
=> Calling out draft pages. Updating formatting

mentoring-wg/2023-meeting-minutes.md
meeting minutes.
Note, this was more of a conversation than a meeting, should probably not be posted to Youtube. @jberkus, @carolynvs
=> 2023-04-11 meeting minutes

programs/lfx-mentorship/2023/02-Jun-Aug/README.md
=> updating LFX term 2 call for proposals dates

.github/labeler.yml
fixes https://github.com/cncf/mentoring/issues/923
/cc @sarvjeetrajvansh @jeefy @RobertKielty for review 🙂
=> updating labeller with mentoring v2 folder structure

programs/lfx-mentorship/2023/03-Sep-Nov/README.md
Updated the broken project idea proposal link in mentoring/programs/lfx-mentorship/2023/03-Sep-Nov/README.md
This PR solves issue  #944
=> Update project idea proposal link

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
Since this project was not selected for GSOC, we would like to propose this as a potential mentorship project for LFX-Mentorship.
=> Add postgres mentorship project for LFX-Mentorship for Armada

programs/lfx-mentorship/2023/02-Jun-Aug/README.md
10th of may is Wednesday not Friday 
mentee applications open date:
Changed Fri May 10 to Wed May 10
=> Changed Fri May 10 to Wed May 10

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
- Implement DNS visibility with KubeArmor - https://github.com/kubearmor/KubeArmor/issues/1219
- Manage KubeArmor policies using OCI registry and use OCI hooks for container events - https://github.com/kubearmor/KubeArmor/issues/1130
=> add KubeArmor LFX Term-2 projects

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
- Description: This project aims to improve the user experience with the chaos workflow GraphQL APIs by enhancing their functionality and addressing security vulnerabilities. The project includes converting the user-facing chaos workflow and workflow run APIs, refactoring the chaos-workflow package into interfaces and splitting it into separate packages, and resolving security vulnerabilities and golangci-lint issues in the chaos-center backend components. 
- Expected outcome: The outcome of this project will be improved functionality, security, and usability of the chaos workflow GraphQL APIs and chaos-center backend components through the implementation of new features, refactoring of existing code, and addressing of security vulnerabilities.
- Recommended Skills:
- Golang
- Kubernetes …
=> Adding 2 project ideas for litmuschaos for LFX Q2

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
This PR updates the upstream issue link for Konveyor
Background: The issue was created in the wrong repo. It has been recreated in the right repo. Apologies for any inconvenience
cc: @nate-double-u
=> update konveyor upstream link

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
* [Store Kubescape configuration scan results as CRs](https://github.com/kubescape/kubescape/issues/1225)
* [Prometheus exporter for image vulnerabilities](https://github.com/kubescape/kubescape/issues/1226)
* [Vulnerability-based Dockerfile generator](https://github.com/kubescape/kubescape/issues/1227)
=> Add Kubescape proposals for Term 2

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
=> UX UI initiative proposal

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>
=> Service Mesh Performance lfx-sumer-03

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
@nate-double-u I want to add two ORAS proposals to the LFX mentorship term 2. Let me know if any additional information is needed. Thanks.
=> add two proposals for Notary to LFX mentorship term 2

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
@nate-double-u I want to add one proposal to term 2. Please let me know if anything more is needed.
So sorry we are late. It would so appreciated if we can participate this term of mentorship.
=> Add KubeVela proposal for LFX mentorship term 2

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
@nate-double-u I want to add two ORAS proposals to the LFX mentorship term 2. Thanks
=> add ORAS proposals to LFX mentorship term2

programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md
This PR adds the Vitess `Rework the frontend UI of Vitess’ benchmarking tools` project to the list of project ideas for the LFX internship June-August in 2023.
=> Add Vitess/Arewefastyet project proposal for LFX internship

programs/lfx-mentorship/2023/02-Jun-Aug/README.md
I would like to add Asmit Malakannawar @asmitbm as a new mentor to the ORAS project
=> add Asmit Malakannawar as a new mentor to ORAS project

programs/lfx-mentorship/2023/02-Jun-Aug/README.md
#987 but against readme.md instead of project_ideas.md.
=> Update a missing heading

mentoring-wg/gsoc-org-admin-guide.md, programs/program-statistics.md
Update GSoC org admin guide with the new announcements
=> Update GSoC org admin guide with the new announcements

mentoring-wg/gsoc-org-admin-guide.md
Update GSoC admin guide with instructions about coding start
=> Update GSoC admin guide with instructions about coding start

.github/settings.yml
=> updating "help-wanted" label to "help wanted"

mentoring-wg/2023-meeting-minutes.md
Updating
* upcoming meeting (June 13)
Adding
* May 23
* May 9
* Apr 25
Removing 
* unused sections throughout
=> Updating mentoring wg meeting minutes

README.md, programs/README.md, programs/lfx-mentorship/README.md
Updating program statistics and lists.
~/hold - we're still waiting on one evaluation~
fixes: https://github.com/cncf/mentoring/issues/910
=> Updating 2022 term 3 & 2023 term 1 program stats

.github/workflows/prlabeler.yml
=> Fixed PR Labeler Action

mentoring-wg/gsoc-org-admin-guide.md, mentoring-wg/gsoc-selection-and-ranking-process.md
Document GSoC project selection and ranking process
Based on the discussion here: https://github.com/cncf/mentoring/discussions/860
=> Document GSoC project selection and ranking process

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Project idea for Armada for Fall LFX Mentorship
=> add virtual-kubelet provider for armada to LFX ideas

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Signed-off-by: Chip Zoller <chipzoller@gmail.com>
=> add Kyverno mentorships

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Signed-off-by: Craig Box <craigb@armosec.io>
=> Add two project ideas for Kubescape

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Adding Thanos query observability project for sep-nov term.
cc: @GiedriusS for review 🙂
=> LFX Sep-Nov 2023: Add Thanos query o11y project

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
=> docs: add proposals related to Konveyor Move2Kube

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Drafted for Lin to look at tomorrow, and approve by comment by the 5pm PST deadline.
Please note that the lead mentors will probably change, and we have a pool of maintainers who can augment the project based on the location of any students selected.
Signed-off-by: Craig Box <craigb@armosec.io>
=> Add two project ideas for Istio

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Adding another Thanos LFX project.
=> Add Thanos distributed query engine project

programs/lfx-mentorship/2023/03-Sep-Nov/README.md
alphabetizing accepted projects list
updating mentor emails
creating table of contents
=> Updating 2023 term 3 accepted projects list

programs/lfx-mentorship/2023/03-Sep-Nov/README.md, programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Please do not merge till projects are approved by LFX.
=> Enrolling KubeArmor in LFX 2023 Term 3 Sep-Nov projects

programs/lfx-mentorship/2023/03-Sep-Nov/project_ideas.md
Add project ideas  for KubeEdge community.
=> Add project_ideas for KubeEdge

programs/lfx-mentorship/2023/03-Sep-Nov/README.md
I will be leaving GR and not able to focus on projects like Armada.  I am removing this project from consideration.
=> remove armada project

programs/lfx-mentorship/2023/03-Sep-Nov/README.md
Hello @nate-double-u, this PR adds the proposal for the Vitess' LFX project during the next term.
=>  Enrolling Vitess in LFX 2023 Term 3 Sep-Nov projects

README.md
Fixed typo at line 14: repositery -> repository.
=> Fixed typo at line number 14

programs/seasonofdocs/README.md
with reference to issue #997 I have made the require changes
=> Flux and WasmEdge details added

.github/labeler.yml, programs/lfx-mentorship/2024/01-Mar-May/README.md, programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Resolves #1070 
deploy preview:
* https://github.com/nate-double-u/cncf-mentoring/blob/add-lfx-2024-term-1/programs/lfx-mentorship/2024/01-Mar-May/README.md
* https://github.com/nate-double-u/cncf-mentoring/blob/add-lfx-2024-term-1/programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
| activity | date |
| --- | --- |   
| project proposals | Monday Jan 8 - Wednesday Jan 24, 8:00 AM PDT |
| mentee applications open | Monday Jan 29 - Tues Feb 13, 5:00 PM PDT |
| application review/admission decisions | Wed Feb 14 - Tues Feb 27, 5:00 PM PDT |
| selection notifications | Tues Feb 27, 5:00 PM PDT |
| Mentorship program begins with the initial work assignments | Monday March 4 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | Wednesday April 10 (Week 6) |
| Final mentee …
=> Add lfx 2024 Term 1

mentoring-wg/2023-meeting-minutes.md
Mentorship WG Meeting minutes for Sept 12, 2023
=> 2023-09-12 meeting minutes

mentoring-wg/2023-meeting-minutes.md
2023-10-10 Mentoring WG meeting minutes
=> 2023-10-10 Mentoring WG meeting minutes

README.md, programs/README.md, programs/lfx-mentorship/2023/03-Sep-Nov/README.md
Adding table of successful 2023 LFX Term 3 projects
=> adding listing of successful 2023 LFX Term 3 projects

mentoring-wg/2023-meeting-minutes.md
Adding 2023-12-12 Meeting minutes
=> meeting-minutes-2023-12-12

programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
Upstream issue https://github.com/jaegertracing/jaeger/issues/5084
=> Add Jaeger projects for 2024 Term-1

programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
One of our issues had a wrong link on it, I have updated it.
cc: @aliok
=> Fix Kubearmor issue link

programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
This PR adds Cloud Native Buildpacks as part of the LFX mentorship program.
cc @natalieparellano and @jjbustamante
=> Add 2024 lfx cnb project

programs/lfx-mentorship/2024/01-Mar-May/README.md, programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
=> Submitting LFX 2024 Term 1 Mar-May projects for LFX approval

programs/lfx-mentorship/2024/01-Mar-May/README.md, programs/lfx-mentorship/2024/01-Mar-May/project_ideas.md
=> Submitting late LFX 2024 term 1 projects for LFX approval

programs/lfx-mentorship/2024/01-Mar-May/README.md
Hello :) ,
We would like to add two new mentors and re-send an invite to Alex if possible.
Thanks in advance !
=> Add K8sGPT mentors and update email address

programs/lfx-mentorship/2024/01-Mar-May/README.md
=> updating formatting on LFX 2024 term 1 README.

programs/summerofcode/2024.md
Thanks @aslom, @matzew and @lkingland!
Could you give a thumbs up please?
=> Add Knative idea to GSoC 2024

programs/summerofcode/2024.md
- Add a missing header
- Sort alphabetically
=> Organize GSoC ideas page

programs/summerofcode/2024.md
=> formatting updates in GSoC 2024 README file

programs/summerofcode/2024.md
cc @macxamin @arthurSens @TheSpiritXIII @cstyan
=> Added 2 Prometheus projects to GSoC 2024

programs/summerofcode/2024.md
Adding expected project size to Service Mesh Performance GSoC 2024 proposal
=> Updating GSoC 2024 project proposals

programs/summerofcode/2024.md
Standardize GSoC ideas page formatting
=> Standardize GSoC ideas page formatting

programs/summerofcode/2024.md
Hey, I'm Tony Jin, one of the contributor (maintainer) from the Kubebuilder community.
@camilamacedo86 has briefly talk with me around this project and I am very looking forward join as a mentor.
=> Update 2024.md - Add tony to Kubebuilder

programs/lfx-mentorship/2024/01-Mar-May/README.md
@nate-double-u We previously entered Cwen Yin’s email address incorrectly and apologized for any trouble this may have caused. 🙇‍♂️
=> Correct the email of Cwen Yin at Chaos Mesh project

programs/lfx-mentorship/2024/01-Mar-May/README.md
=> adding Flux to approved projects

programs/summerofcode/2024.md
Hi, I'm Junhao, a mentee at Kubebuilder community last year.
After communicating with @camilamacedo86 , I volunteer to be a mentor at Kubebuilder community this year.
Glad to try my best to help. 😎
=> Update 2024.md - Add Junhao to kubebuilder

programs/summerofcode/2024.md
cc @adityasaky @SantiagoTorres @lukpueh
=> Add in-toto GSoC Project Idea

programs/lfx-mentorship/2024/02-Jun-Aug/README.md
Rectified application review/admission decisions dates from JUNE 29 to MAY 29 and removed duplicate days.
=> rectified application review dates (LFX-mentorship Term 2)

programs/lfx-mentorship/2024/01-Mar-May/README.md
I have changed my GitHub username following https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username.
=> change @astencel-sumo to @andrzej-stencel

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
=> Add Thanos LFX project idea for LFX Jun-Aug 2024

.github/labeler.yml
Updating autolabeller for LFX 2024 terms 2 & 3.
=> updating auto labeller to include upcoming LFX terms

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Project ideas for [Karmada](https://github.com/karmada-io/karmada) as part of the LFX Mentorship program.
=> Add project ideas for Karmada

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Added Knative proposals for LFX mentorship summer 2024
=> Add Knative Onboarding Research

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Added Kubescape proposals for LFX mentorship summer 2024
=> Add project ideas for Kubescape

programs/lfx-mentorship/README.md
=> Update LFX README.md

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
=> Adding Knative website project

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
This commit adds to the project ideas a proposal from Kubernetes Release Engineering. We are seeking help to fix image signatures in our image promotion process.
/hold 
For final RelEng review
/cc @mehabhalodiya
=> Add Image Signing From K8s RelEng

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
=> Add Prometheus OOO mentorship idea

programs/lfx-mentorship/2024/03-Sep-Nov/README.md, programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
Setting up CNCF LFX 2024 Term 3 Sept-Nov
resolves #1107
=> Adding CNCF LFX 2024 Term 3 Sept-Nov

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
cc @daemon1024 @kranurag7 @PrimalPimmy
=> KubeArmor project ideas for LFX 2024 Jun-Aug

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Sort LFX projects alphabetically
=> Sort LFX projects alphabetically

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
We have a new parent issue for the Knative website project, updating the link to point to that
=> fix: use parent issue for Knative website improvement project

programs/lfx-mentorship/2024/02-Jun-Aug/project_ideas.md
Proposal for Copacetic Project for LFX 2024 Jun-Aug
=> Proposal for Copacetic Project for LFX 2024 Jun-Aug

programs/lfx-mentorship/README.md
=> Mentorship > Communication: clarify contacts, DOs and DON'Ts

programs/lfx-mentorship/2024/01-Mar-May/README.md
To set the record straight. Yash was helping out in the Spring term but was not officially listed.
=> Add Yash Sharma as mentor

programs/lfx-mentorship/2024/02-Jun-Aug/README.md
=> [TUF] Use new terminology of docs analysis

programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
@nate-double-u I just realized the typo in my name once the PR got merged. apologies for the inconvenience
=> Fixing the typo in my name

programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
Add Inspektor Gadget project proposals for LFX mentorship program 2024 term 3.
cc @alban @flyth @mqasimsarfraz @burak-ok
=> Inspektor Gadget project proposals for LFX 2024 term 3

programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
cc @juntao @q82419
Please leave 👍 or approve this PR to ensure your participation.
=> add wasmedge lfx 2024-03 projects

programs/lfx-mentorship/2024/03-Sep-Nov/README.md
Given the low number of proposals, we should consider rescheduling part of the term to give maintainers more time to get their ideas together.
New schedule proposal (updates in bold):
| activity                                                                                                     | date                                                                                |
|--------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|   
| project proposals                                                                                            | Jul 3 - **Jul 30** 5:00 PM PDT                                                          |
| mentee …
=> update lfx 2024 term 3 schedule

programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
Add two jaeger mentorship projects for lfx 2024 03-Sep-Nov cycle
cc : @yurishkuro
=> Add two jaeger mentorship projects for lfx 2024 03-Sep-Nov cycle

programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
This PR propose a project for Vitess. cc @mattlord
https://github.com/vitessio/website/issues/1798
=> Propose idea for vitess term 3 of 2024

programs/lfx-mentorship/2024/03-Sep-Nov/README.md, programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
Please don't merge till LFX approvals are in.
=>  LFX 2024 term 3 approvals - batch 3

programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
xlink: https://github.com/kubernetes/kubernetes/issues/126369
I will try to find out if anybody from SIG Docs can help. I have limited knowledge of hugo and automation possible on website.
=> pod lifecycle events project

programs/lfx-mentorship/2024/03-Sep-Nov/README.md, programs/lfx-mentorship/2024/03-Sep-Nov/project_ideas.md
Please don't merge till LFX approvals are done.
=>  LFX 2024 term 3 approvals - batch 5

programs/lfx-mentorship/2024/01-Mar-May/README.md, programs/lfx-mentorship/2024/02-Jun-Aug/README.md, programs/lfx-mentorship/2024/03-Sep-Nov/README.md, programs/lfx-mentorship/2025/01-Mar-May/README.md, programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Some key dates considered:
* KubeCon/CloudNativeCon Europe: April 1-4, 2025
We may make some updates, but I wanted to get something on the calendar to work from and share.
=> Plan LFX 2025 term 1

mentoring-wg/2024-meeting-minutes.md
Oct 17 2024 meeting minutes
formatting updates throughout
=> adding Mentoring WG meeting minutes for Oct 17, 2024

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Creating it as a draft since we're still figuring out the details for the second project :)
=> Add project proposals for Prometheus

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Creating it as a draft since we're still discussing it.
cc @mauriciovasquezbernal @eiffel-fl @alban @blanquicet
=> Add Inspektor Gadget projects for 2025 Term 1

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Add Karmada LFX 2025 term1 ideas. PTAL 😄
=> Add Karmada projects for 2025 LFX term1

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
=> Add Headlamp projects for 2025 Term 1

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Updating:
* formatting
* upstream issues
=> updating LFX 2025 T1 proposed issues formatting upstream issues

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Add Kmesh LFX 2025 term1 ideas. PTAL 😄
=> add LFX 2025 term1 Kmesh projects

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Pull forward changes from #1271, which were deferred from Term 3 2024 for health reasons.
=> add Istio Docs WG projects

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
=> adding upstream issue for KubeStellar UI project

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
CNCF / LFX Mentorship projects submission for Microcks.
=> LFX: Add Microcks projects for Term 01

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Hi team,
This PR adds the proposed projects for LFX Term 1 for LitmusChaos. Thanks for taking a look.
=> LFX: Adding LitmusChaos projects for Term 01

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
This adds two Knative projects for LFX term 1, both focused on the educational game we have been developing in the UX WG.
=> feat: add knative projects for 2025 term 1

programs/lfx-mentorship/2025/01-Mar-May/project_ideas.md
Looks like it was mangled in a PR.
/cc @GiedriusS for awareness (please open  a new PR if i've made this more incorrect. I'm going to merge this quick so we can load it into LFX and get their approval process going)
=> correcting Thanos proposal

programs/lfx-mentorship/2025/01-Mar-May/README.md
=> update mentor email address

programs/summerofcode/2025.md
Hi @nate-double-u,  
I am not sure if there is a limitation on the number of submitted project ideas. I have already sorted the priority of these three ideas. Please remove them from the back if the GSoC program doesn't allow us to have multiple entries. Thanks.
=> add WasmEdge GSoC 2025 project ideas

programs/summerofcode/2025.md
Hi team, adding a task for LitmusChaos for GSoC 2025. Thanks for taking a look.
=> GSoC 2025: Adding LitmusChaos task for GSoC

programs/summerofcode/2025.md
Creating raw draft of the proposal for etcd caching. Can provide more details when I'm back from vacation.
https://github.com/etcd-io/etcd/issues/19371
=> Add etcd cache project

programs/summerofcode/2025.md
=> feat: add kcl project for GSoC

programs/summerofcode/2025.md
Adding Harbor Satellite Idea to GSOC 2025.
cc // @Vad1mo, @OrlinVasilev
=> Add Harbor Ideas to GSOC 2025

programs/summerofcode/2025.md
=> Add TUF GSOC project idea

programs/summerofcode/2025.md
cc @nate-double-u  @MadhavJivrajani
=> Update the etcd project description and add second mentor

programs/lfx-mentorship/2025/01-Mar-May/README.md, programs/lfx-mentorship/2025/02-Jun-Aug/README.md, programs/lfx-mentorship/2025/03-Sep-Nov/README.md
Updating LFX 2025 program dates with times for when activities need to be completed by.
=> Updating LFX 2025 program dates/times

programs/summerofcode/2025.md
Adding a Knative Functions proposal for GSOC 2025.
=> GSoC 2025: Functions

programs/lfx-mentorship/2025/01-Mar-May/README.md
Re-adding Kyverno Chainsaw Tests for New Policy Types project to LFX 2025 Term 1
/cc @realshuting @JimBugwadia @eddycharly
=> Re-adding Kyverno project to LFX 2025 Term 1

programs/lfx-mentorship/2025/01-Mar-May/README.md
Adding myself (ilrudie) to Istio mentor list.
cc @kfaseela
=> Update Istio mentor list

programs/summerofcode/2025.md
This PR updates the mentor list for KubeStellar project - AI/ML Model Monitoring and Drift Detection in Disconnected Clusters using KubeStellar
=> Update mentor list for KubeStellar

programs/summerofcode/2025.md
Signed-off-by: myan <myan@redhat.com>
=> GSoC 2025: Extend Proposal Content for Open Cluster Management

programs/summerofcode/2025.md
This PR achieves the following:
-     Updates the KubeStellar project description
-     Adds another secondary mentor to the list
=> Updating KubeStellar project description

programs/summerofcode/2025.md
This PR adds another secondary mentor to the KubeStellar project.
=> Adding a new mentor to  KubeStellar project

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
=> Add project ideas for KubeStellar LFX term2 

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Add Kubernetes kubeadm related idea.
=> Add kubernetes kubeadm related idea

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
This PR adds a Kubeflex Project Proposal to the KubeStellar list of projects
=> Adding KubeFlex Project Proposal to KubeStellar 

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Revise the project descriptions and expected outcomes for the KubeStellar plugin system and UI modernization to clarify objectives and enhance user experience.
=> Refactor KubeStellar project ideas and update plugin marketplace description

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Potential Cartography 2025 summer mentor project!
=> Cartography project - Summer 2025

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Add OpenKruise LFX 2025 term 2 ideas.
=> add openkruise ideas

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
We've got a pretty cool project idea for somebody - we have just built an integration test pipeline and are looking for great testing! We have laid out the OpenCost test plan in the linked ticket and will continue to curate that - we are looking for help building these! 
What do you think @nate-double-u ?
=> add mentorship project idea for OpenCost

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Implementing “Declarative Management of PostgreSQL Foreign Data Wrappers” in CloudNativePG as part of LFX Mentorship Program (2025, term 02).
Adding also @armru, @leonardoce and @mnencia as mentors.
=> add mentorship project idea for CloudNativePG

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Adding "ambient multi-cluster testing" in Istio as part of LFX Mentorship Program (2025, term 02).
Also have @stevenjin8 as a mentor
=> project idea (istio): ambient multi-cluster testing

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
We would like to join the LFX 2025 term 2, and this PR contains some ideas for PipeCD project
Please check when you have time @nate-double-u 😄
=> Submit proposals for PipeCD project

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Add Harbor LFX 2025 term 2 ideas.
cc // @Vad1mo, @OrlinVasilev
=> Add Harbor Projects for LFX Term 2

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
=> UX/UI Mentorship for Kubestellar

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Hi, team
This PR adds Scenario rollback feature to krkn chaos tool for Term 02 - 2025 Jun - Aug.
=> LFX: Krkn scenario rollback feature for Term 02 - 2025 Jun - Aug

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Copacetic Mentorship application for LFX mentorship program.
=> Update project_ideas for Project Copacetic

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
@nate-double-u we would like to add an additional mentor here. I will ask @mbolt35 to approve this PR as an acknowledgement
=> add mentor for opencost project

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Hi, these two project ideas are not selected by GSoC. So we transfer them to the LFX mentorship 2025 term 2.
=> wasmedge: Transfer project ideas from gsoc to lfx 2025-02

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Hi, team
This PR adds Volcano projects for Term 02 - 2025 Jun - Aug.
cc @kevin-wangzefeng @william-wang, the maintainers, please give a thumb to confirm this: )
=>  LFX: Add Volcano projects for Term 02 - 2025 Jun - Aug

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
cc @yolossn @illume @knrt10 @joaquimrocha @ivelisseca
=> Add Headlamp projects for Term 02 - 2025 Jun - Aug

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
little bit late, but wanted to add one more for the https://github.com/kgateway-dev/kgateway project
cc @npolshakova @lgadban
=> kgateway: AI observability project

programs/lfx-mentorship/2025/02-Jun-Aug/project_ideas.md
Add KubeEdge LFX 2025 term2 ideas. PTAL 😄
cc @HongbingZhang @liyuerich @meixiezichuan @wbc6080 @MooreZheng @IcyFeather233 and please give a thumb to confirm this: )
=> Add KubeEdge projects for 2025 LFX term2

programs/lfx-mentorship/2025/02-Jun-Aug/README.md
(Sorry for cutting it close to the wire; I've been on dad duty while mum has been sick the past week.)
Add Istio docs project, and make copy edits to Istio multi-cluster project.
=> Add Istio docs project

programs/lfx-mentorship/2025/02-Jun-Aug/README.md
This PR updates the maintainer/mentor details for the **KubeStellar: Marketplace UI and UI Optimization** project under the CNCF - LFX Mentorship Program for **2025 Term 2 (Jun-Aug)**.
The following updates have been made:
- Update maintainer details in KubeStellar Marketplace UI project for 2025.
cc: @clubanderson
=> Update maintainer details in KubeStellar Marketplace UI project for 2025

programs/lfx-mentorship/README.md
Adding additional instruction to the LFX Mentee Selection process.
=> updating LFX mentee selection process

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
adds a project proposal for OpenCost. @mbolt35 and myself will serve as mentors
=> [OpenCost] [Project Proposal] OpenCost MCP Server

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Add a project for 2025 term 3, to address https://github.com/kubestellar/kubestellar/issues/3072
=> Add 2025t3 project for kubestellar/kubestellar/issues/3072

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
This PR adds the Model Context Protocol and A2A Communication framework project for Kubestellar UI 2025 Sep-Nov term LFX Mentorship term.
issue: https://github.com/kubestellar/ui/issues/1481 (https://github.com/kubestellar/ui/issues/1481)
=> Add Model Context Protocol project for KubeStellar UI 2025 Sep-Nov term

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
=> add Kubestellar for LFX sept-nov term

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
=> Add Podman project idea for 2025-03 LFX mentoring

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
=> add kubeadm task for 03-Spe-Nov

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Documentation, Chaos Testing and CNPG-I Hello world
=> CloudNativePG: 2025-3 proposals

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Adds project proposals for the LFX 2025 term for https://github.com/cartography-cncf/cartography.
This includes
Resource Permission Relationships for Azure and GCP:
- https://github.com/cartography-cncf/cartography/issues/1734
- https://github.com/cartography-cncf/cartography/issues/1735
Coverage for Azure and GCP
- https://github.com/cartography-cncf/cartography/issues/1736
- https://github.com/cartography-cncf/cartography/issues/415
=> Add Cartography LFX 2025 Fall projects

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
cc @zmberg @AiRanthem @chrisliu1995 @ringtail
=> add openkruise ideas for LFX mentorship term3 

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Add Kmesh LFX 2025 term3 ideas. PTAL 😄
cc @hzxuzhonghu @yaozegzeng and please give a thumb to confirm this: )
=> Kmesh 2025 LFX terms project ideas

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Adds project proposals for the LFX 2025 term for https://github.com/kgateway-dev/kgateway
=> Add kgateway term3 project proposals

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Proposing another project idea from the Prometheus project. 
cc @perebaj
=> LFX Mentorship (Sep-Nov): Prometheus Native Summaries

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
SIG Docs would love an assist improving the tooling we use to generate the Kubernetes API reference docs!
Tagging SIG Contribex leads: @kaslin, @mfahlandt, and @palnabarun
=> Add LFX Mentorship project for Kubernetes API Reference Docs Generator

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
Follow up to: https://github.com/cncf/mentoring/pull/1499 & https://github.com/cncf/mentoring/pull/1486
=> re-adding kubernetes docs generator project

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
This PR adds a Knative LFX project for term 3
cc @lkingland @prajjwalyd
=> feat: add knative ux/func LFX project for 2025 term 3

programs/lfx-mentorship/2025/03-Sep-Nov/project_ideas.md
=> LFX '25 Term 3 - Meshery: GCP Model Relationships
